/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Aircraft;
import Business.FleetOfAircrafts;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eklav
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private FleetOfAircrafts fleetArray;
    public MainJFrame() throws FileNotFoundException{
        initComponents();
        fleetArray = new FleetOfAircrafts();
        dataloading();
    }
    
    public void dataloading() throws FileNotFoundException{
        
        Scanner scan = new Scanner(new File("AircraftData.csv"));
        
        while(scan.hasNextLine()){
            String line = scan.nextLine();//starts from zeroth position
            String[] lineArray = line.split(",");//row seperated by ',' and stored inside the array
            
            Aircraft aircraftFromFile = fleetArray.addAircraft();
            aircraftFromFile.setMakeOfAircraft(lineArray[0]);
            aircraftFromFile.setSerialNum(Integer.parseInt(lineArray[1]));
            aircraftFromFile.setMaintCertification(lineArray[2]);
            aircraftFromFile.setModelNum(Integer.parseInt(lineArray[3]));
            aircraftFromFile.setMakeYear(Integer.parseInt(lineArray[4]));
            aircraftFromFile.setAirport(lineArray[5]);
            aircraftFromFile.setDepartTime(lineArray[6]);
            aircraftFromFile.setNumOfSeats(Integer.parseInt(lineArray[7]));
        }
        
        FleetOfAircrafts refresh = new FleetOfAircrafts();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        startJPanel = new javax.swing.JPanel();
        nEUAirlinesJLabel = new javax.swing.JLabel();
        viewAllManufacturersJButton = new javax.swing.JButton();
        viewAllAircraftsJButton = new javax.swing.JButton();
        searchJButton = new javax.swing.JButton();
        viewAvailableAircraftsJButton = new javax.swing.JButton();
        viewFirstAvailableAircraftsJButton = new javax.swing.JButton();
        txtSearchFirstAvailableJTextField = new javax.swing.JTextField();
        txtSearchAvailableAircraftsJTextField = new javax.swing.JTextField();
        firstAvailableTimeJLabel = new javax.swing.JLabel();
        availableAllAircraftsJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nEUAirlinesJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nEUAirlinesJLabel.setText("NEU Airlines");

        viewAllManufacturersJButton.setText("View All Manufacturers");
        viewAllManufacturersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllManufacturersJButtonActionPerformed(evt);
            }
        });

        viewAllAircraftsJButton.setText("View All Aircrafts");
        viewAllAircraftsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllAircraftsJButtonActionPerformed(evt);
            }
        });

        searchJButton.setText("Search");
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        viewAvailableAircraftsJButton.setText("View Available Aircrafts");
        viewAvailableAircraftsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvailableAircraftsJButtonActionPerformed(evt);
            }
        });

        viewFirstAvailableAircraftsJButton.setText("View FIRST Available Aircrafts");
        viewFirstAvailableAircraftsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFirstAvailableAircraftsJButtonActionPerformed(evt);
            }
        });

        txtSearchFirstAvailableJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFirstAvailableJTextFieldActionPerformed(evt);
            }
        });

        txtSearchAvailableAircraftsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchAvailableAircraftsJTextFieldActionPerformed(evt);
            }
        });

        firstAvailableTimeJLabel.setText("Time");

        availableAllAircraftsJLabel.setText("Airport");

        javax.swing.GroupLayout startJPanelLayout = new javax.swing.GroupLayout(startJPanel);
        startJPanel.setLayout(startJPanelLayout);
        startJPanelLayout.setHorizontalGroup(
            startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewAllAircraftsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAllManufacturersJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(startJPanelLayout.createSequentialGroup()
                        .addGroup(startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewAvailableAircraftsJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewFirstAvailableAircraftsJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstAvailableTimeJLabel)
                            .addComponent(availableAllAircraftsJLabel))
                        .addGap(27, 27, 27)
                        .addGroup(startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchFirstAvailableJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtSearchAvailableAircraftsJTextField)))
                    .addComponent(searchJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nEUAirlinesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        startJPanelLayout.setVerticalGroup(
            startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startJPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(nEUAirlinesJLabel)
                .addGap(18, 18, 18)
                .addComponent(viewAllAircraftsJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewFirstAvailableAircraftsJButton)
                    .addComponent(txtSearchFirstAvailableJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstAvailableTimeJLabel))
                .addGap(18, 18, 18)
                .addGroup(startJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAvailableAircraftsJButton)
                    .addComponent(txtSearchAvailableAircraftsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableAllAircraftsJLabel))
                .addGap(18, 18, 18)
                .addComponent(viewAllManufacturersJButton)
                .addGap(61, 61, 61)
                .addComponent(searchJButton)
                .addGap(575, 575, 575))
        );

        splitPane.setLeftComponent(startJPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchAvailableAircraftsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchAvailableAircraftsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchAvailableAircraftsJTextFieldActionPerformed

    private void txtSearchFirstAvailableJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFirstAvailableJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFirstAvailableJTextFieldActionPerformed

    private void viewFirstAvailableAircraftsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFirstAvailableAircraftsJButtonActionPerformed
        // TODO add your handling code here:
        SearchResultsJPanel searchResultsJPanel = new SearchResultsJPanel(fleetArray);
        splitPane.setRightComponent(searchResultsJPanel);
        int timeForFirstAvailable = Integer.parseInt(txtSearchFirstAvailableJTextField.getText());

    }//GEN-LAST:event_viewFirstAvailableAircraftsJButtonActionPerformed

    private void viewAvailableAircraftsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvailableAircraftsJButtonActionPerformed
        // TODO add your handling code here:
        
        SearchResultsJPanel searchResultsJPanel = new SearchResultsJPanel(fleetArray);
        splitPane.setRightComponent(searchResultsJPanel);
    }//GEN-LAST:event_viewAvailableAircraftsJButtonActionPerformed

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        // TODO add your handling code here:
        SearchResultsJPanel searchResultsJPanel = new SearchResultsJPanel(fleetArray);
        splitPane.setRightComponent(searchResultsJPanel);

    }//GEN-LAST:event_searchJButtonActionPerformed

    private void viewAllAircraftsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllAircraftsJButtonActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewJPanel = new ViewJPanel(fleetArray);
        splitPane.setRightComponent(viewJPanel);
    }//GEN-LAST:event_viewAllAircraftsJButtonActionPerformed

    private void viewAllManufacturersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllManufacturersJButtonActionPerformed
        // TODO add your handling code here:
        SearchResultsJPanel searchResultsJPanel = new SearchResultsJPanel(fleetArray);
        splitPane.setRightComponent(searchResultsJPanel);
    }//GEN-LAST:event_viewAllManufacturersJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableAllAircraftsJLabel;
    private javax.swing.JLabel firstAvailableTimeJLabel;
    private javax.swing.JLabel nEUAirlinesJLabel;
    private javax.swing.JButton searchJButton;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel startJPanel;
    private javax.swing.JTextField txtSearchAvailableAircraftsJTextField;
    private javax.swing.JTextField txtSearchFirstAvailableJTextField;
    private javax.swing.JButton viewAllAircraftsJButton;
    private javax.swing.JButton viewAllManufacturersJButton;
    private javax.swing.JButton viewAvailableAircraftsJButton;
    private javax.swing.JButton viewFirstAvailableAircraftsJButton;
    // End of variables declaration//GEN-END:variables
}
