/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Aircraft;
import Business.FleetOfAircrafts;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eklav
 */
public class SearchResultsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form searchResultsJPanel
     */
    private FleetOfAircrafts fOFA;
  
    public SearchResultsJPanel(FleetOfAircrafts fOFA) {
        initComponents();
        this.fOFA = fOFA;
        
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) searchResultsJTable.getModel();
        dtm.setRowCount(0);
        
        for(Aircraft afct :  fOFA.getFleet() ){
            //System.out.println("S2"+afct.getSerialNum());
            Object row[] = new Object[8];
            row[0] = afct.getMakeOfAircraft();
            row[1] = afct.getSerialNum();
            row[2] = afct.getMaintCertification();
            row[3] = afct.getModelNum();
            row[4] = afct.getMakeYear();
            row[5] = afct.getAirport();
            row[6] = afct.getNumOfSeats();
            row[7] = afct.getDepartTime();
            dtm.addRow(row);
            txtAircraftAvailableJTextField.setText(String.valueOf(dtm.getRowCount()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aircraftDetailsPanelJLabel = new javax.swing.JLabel();
        searchResultsJScrollPane = new javax.swing.JScrollPane();
        searchResultsJTable = new javax.swing.JTable();
        aircraftAvailableJLabel = new javax.swing.JLabel();
        txtAircraftAvailableJTextField = new javax.swing.JTextField();
        searchPanelJLabel = new javax.swing.JLabel();
        searchJButton = new javax.swing.JButton();
        airportLocatedInJLabel = new javax.swing.JLabel();
        manufacturerOfAircraftJLabel = new javax.swing.JLabel();
        txtSearchManufacturerOfAircraftJTextField = new javax.swing.JTextField();
        txtSearchSerialNumberJTextField = new javax.swing.JTextField();
        txtSearchMaintenanceCertificateDateJTextField = new javax.swing.JTextField();
        departureTimeJLabel = new javax.swing.JLabel();
        txtSearchModelNumberJTextField = new javax.swing.JTextField();
        yearOfManufactureJLabel = new javax.swing.JLabel();
        txtSearchYearOfManufactureJTextField = new javax.swing.JTextField();
        txtSearchAirportLocatedInJTextField = new javax.swing.JTextField();
        serialNumberJLabel = new javax.swing.JLabel();
        expiredMaintenanceCertificateJLabel = new javax.swing.JLabel();
        modelNumberJLabel = new javax.swing.JLabel();
        numberOfSeatsAvailableJLabel = new javax.swing.JLabel();
        txtSearchDepartureTimeJTextField = new javax.swing.JTextField();
        txtSearchNumberOfSeatsAvailableJTextField = new javax.swing.JTextField();

        aircraftDetailsPanelJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aircraftDetailsPanelJLabel.setText("Search Results");

        searchResultsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer", "Serial Number", "Maintenance Certification", "Model Number", "Year of Manufacture", "Airport Located", "Number of Seats", "Departure Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchResultsJScrollPane.setViewportView(searchResultsJTable);

        aircraftAvailableJLabel.setText("Aircrafts Available:");

        txtAircraftAvailableJTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        searchPanelJLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        searchPanelJLabel.setText("Search Panel");

        searchJButton.setText("Search");
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        airportLocatedInJLabel.setText("Airport Located in (E/F/G/H):");

        manufacturerOfAircraftJLabel.setText("Manufacturer of Aircraft (A/B/C/D):");

        txtSearchSerialNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSerialNumberJTextFieldActionPerformed(evt);
            }
        });

        departureTimeJLabel.setText("Departure Time (00 to 24):");

        yearOfManufactureJLabel.setText("Year of Manufacture (2000 to 2017):");

        serialNumberJLabel.setText("Serial Number (1 to 100):");

        expiredMaintenanceCertificateJLabel.setText("Expired Maintenance Certificate (Y/N):");

        modelNumberJLabel.setText("Model Number (10 to 20):");

        numberOfSeatsAvailableJLabel.setText("Number of Seats Available (01 to 250):");

        txtSearchDepartureTimeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDepartureTimeJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(aircraftDetailsPanelJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aircraftAvailableJLabel)
                                .addGap(40, 40, 40)
                                .addComponent(txtAircraftAvailableJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchResultsJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberOfSeatsAvailableJLabel)
                                    .addComponent(serialNumberJLabel)
                                    .addComponent(manufacturerOfAircraftJLabel)
                                    .addComponent(expiredMaintenanceCertificateJLabel)
                                    .addComponent(modelNumberJLabel)
                                    .addComponent(yearOfManufactureJLabel)
                                    .addComponent(airportLocatedInJLabel)
                                    .addComponent(departureTimeJLabel))
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchMaintenanceCertificateDateJTextField)
                                    .addComponent(txtSearchManufacturerOfAircraftJTextField)
                                    .addComponent(txtSearchNumberOfSeatsAvailableJTextField)
                                    .addComponent(txtSearchAirportLocatedInJTextField)
                                    .addComponent(txtSearchSerialNumberJTextField)
                                    .addComponent(txtSearchYearOfManufactureJTextField)
                                    .addComponent(txtSearchDepartureTimeJTextField)
                                    .addComponent(txtSearchModelNumberJTextField)
                                    .addComponent(searchJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(searchPanelJLabel)
                                .addGap(223, 223, 223)))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aircraftDetailsPanelJLabel)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aircraftAvailableJLabel)
                            .addComponent(txtAircraftAvailableJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(searchResultsJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPanelJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manufacturerOfAircraftJLabel)
                            .addComponent(txtSearchManufacturerOfAircraftJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serialNumberJLabel)
                            .addComponent(txtSearchSerialNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expiredMaintenanceCertificateJLabel)
                            .addComponent(txtSearchMaintenanceCertificateDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelNumberJLabel)
                            .addComponent(txtSearchModelNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearOfManufactureJLabel)
                            .addComponent(txtSearchYearOfManufactureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airportLocatedInJLabel)
                            .addComponent(txtSearchAirportLocatedInJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departureTimeJLabel)
                            .addComponent(txtSearchDepartureTimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfSeatsAvailableJLabel)
                            .addComponent(txtSearchNumberOfSeatsAvailableJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addComponent(searchJButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        // TODO add your handling code here:
        String manufacturer = txtSearchManufacturerOfAircraftJTextField.getText();
        String serialNum = txtSearchSerialNumberJTextField.getText();
        String maintCertificate = txtSearchMaintenanceCertificateDateJTextField.getText();
        String modelNum = txtSearchModelNumberJTextField.getText();
        String yearOfManufacturer = txtSearchYearOfManufactureJTextField.getText();
        String airportLocated = txtSearchAirportLocatedInJTextField.getText();
        String deptTime = txtSearchDepartureTimeJTextField.getText();
        String seatAvailable = txtSearchNumberOfSeatsAvailableJTextField.getText();

        FleetOfAircrafts searchResults = fOFA.searchAllAircraft(manufacturer, serialNum, maintCertificate, modelNum, yearOfManufacturer,
            airportLocated, deptTime, seatAvailable);
        System.out.println(searchResults.getFleet());
        populateTable();
       
    }//GEN-LAST:event_searchJButtonActionPerformed

    private void txtSearchSerialNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSerialNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSerialNumberJTextFieldActionPerformed

    private void txtSearchDepartureTimeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDepartureTimeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDepartureTimeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aircraftAvailableJLabel;
    private javax.swing.JLabel aircraftDetailsPanelJLabel;
    private javax.swing.JLabel airportLocatedInJLabel;
    private javax.swing.JLabel departureTimeJLabel;
    private javax.swing.JLabel expiredMaintenanceCertificateJLabel;
    private javax.swing.JLabel manufacturerOfAircraftJLabel;
    private javax.swing.JLabel modelNumberJLabel;
    private javax.swing.JLabel numberOfSeatsAvailableJLabel;
    private javax.swing.JButton searchJButton;
    private javax.swing.JLabel searchPanelJLabel;
    private javax.swing.JScrollPane searchResultsJScrollPane;
    private javax.swing.JTable searchResultsJTable;
    private javax.swing.JLabel serialNumberJLabel;
    private javax.swing.JTextField txtAircraftAvailableJTextField;
    private javax.swing.JTextField txtSearchAirportLocatedInJTextField;
    private javax.swing.JTextField txtSearchDepartureTimeJTextField;
    private javax.swing.JTextField txtSearchMaintenanceCertificateDateJTextField;
    private javax.swing.JTextField txtSearchManufacturerOfAircraftJTextField;
    private javax.swing.JTextField txtSearchModelNumberJTextField;
    private javax.swing.JTextField txtSearchNumberOfSeatsAvailableJTextField;
    private javax.swing.JTextField txtSearchSerialNumberJTextField;
    private javax.swing.JTextField txtSearchYearOfManufactureJTextField;
    private javax.swing.JLabel yearOfManufactureJLabel;
    // End of variables declaration//GEN-END:variables
}
