/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SMAdminInterface;

import Business.Market.MarketCatalog;
import Business.MarketOffers.MarketOfferCatalog;
import Business.PersonPackage.PersonDirectory;
import Business.PersonPackage.SalesPerson;
import Business.Sales.OrderCatalog;
import Business.SupplierPackage.SupplierDirectory;
import Business.UserAccountPackage.UserAccount;
import Business.UserAccountPackage.UserAccountDirectory;
import UserInterface.SMAdminInterface.CompanyPerformanceInterface.CompanyPerformanceJPanel;
import UserInterface.SMAdminInterface.ManageMarketCatalog.ManageMarketJPanel;
import UserInterface.SMAdminInterface.ManagePersonDirectoryInterface.ManagePersonDirectoryJPanel;
import UserInterface.SMAdminInterface.ManageSupplierDirectoryInterface.ManageSupplierDirectoryJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author eklav
 */
public class SMAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    UserAccount foundUserAccount;
    JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;
    PersonDirectory personDirectory;
    UserAccountDirectory userAccountDirectory;
    MarketCatalog marketCatalog;
    MarketOfferCatalog marketOfferCatalog;
    OrderCatalog orderCatalog;
    SalesPerson salesPerson;

    /**
     * Creates new form HRAdminWorkAreaJPanel
     */
    public SMAdminWorkAreaJPanel(UserAccount foundUserAccount, JPanel userProcessContainer, PersonDirectory personDirectory, 
            UserAccountDirectory userAccountDirectory, SupplierDirectory supplierDirectory, MarketCatalog marketCatalog,
            MarketOfferCatalog marketOfferCatalog, OrderCatalog orderCatalog, SalesPerson salesPerson) {
        initComponents();
        this.foundUserAccount = foundUserAccount;
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.userAccountDirectory = userAccountDirectory;
        this.supplierDirectory = supplierDirectory;
        this.marketCatalog = marketCatalog;
        this.marketOfferCatalog = marketOfferCatalog;
        this.orderCatalog = orderCatalog;
        
        this.salesPerson = salesPerson;
        
        txtSMAdminID.setText(String.valueOf(foundUserAccount.getUserID()));
        txtSMAdminName.setText(foundUserAccount.getPerson().getFirstName()+" "+foundUserAccount.getPerson().getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManagePersonDirectory = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblSMAdminID = new javax.swing.JLabel();
        lblSMAdminName = new javax.swing.JLabel();
        txtSMAdminID = new javax.swing.JTextField();
        txtSMAdminName = new javax.swing.JTextField();
        btnLogOut = new javax.swing.JButton();
        lblAdministratorWorkArea = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        btnManageSupplierDirectory = new javax.swing.JButton();
        btnManageMarketCatalogue = new javax.swing.JButton();
        btnReviewCompanyPerformance = new javax.swing.JButton();

        btnManagePersonDirectory.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnManagePersonDirectory.setText("Manage Person Directory >>");
        btnManagePersonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonDirectoryActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Sales & Marketing Adminstrator");

        lblSMAdminID.setText("S&M Adminstrator User ID:");

        lblSMAdminName.setText("S&M Adminstrator Name:");

        txtSMAdminID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSMAdminID.setDisabledTextColor(new java.awt.Color(0, 0, 149));
        txtSMAdminID.setEnabled(false);

        txtSMAdminName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSMAdminName.setDisabledTextColor(new java.awt.Color(0, 0, 149));
        txtSMAdminName.setEnabled(false);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblAdministratorWorkArea.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblAdministratorWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministratorWorkArea.setText("S&M Adminstrator Work Area");

        btnManageSupplierDirectory.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnManageSupplierDirectory.setText("Manage Supplier Directory >>");
        btnManageSupplierDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSupplierDirectoryActionPerformed(evt);
            }
        });

        btnManageMarketCatalogue.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnManageMarketCatalogue.setText("Manage Market Catalogue >>");
        btnManageMarketCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketCatalogueActionPerformed(evt);
            }
        });

        btnReviewCompanyPerformance.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnReviewCompanyPerformance.setText("Review Company's Performance >>");
        btnReviewCompanyPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewCompanyPerformanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdministratorWorkArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSMAdminID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSMAdminName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSMAdminID)
                            .addComponent(txtSMAdminName)))
                    .addComponent(btnManagePersonDirectory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageSupplierDirectory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageMarketCatalogue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReviewCompanyPerformance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addComponent(btnLogOut)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(lblWelcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSMAdminID)
                    .addComponent(txtSMAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSMAdminName)
                    .addComponent(txtSMAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAdministratorWorkArea)
                .addGap(18, 18, 18)
                .addComponent(btnManagePersonDirectory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageSupplierDirectory)
                .addGap(55, 55, 55)
                .addComponent(btnManageMarketCatalogue)
                .addGap(55, 55, 55)
                .addComponent(btnReviewCompanyPerformance)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePersonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonDirectoryActionPerformed
        // TODO add your handling code here:
        ManagePersonDirectoryJPanel panel = new ManagePersonDirectoryJPanel(userProcessContainer, personDirectory, userAccountDirectory);
        userProcessContainer.add("ManageUserAccountsJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePersonDirectoryActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManageSupplierDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSupplierDirectoryActionPerformed
        // TODO add your handling code here:
        ManageSupplierDirectoryJPanel panel = new ManageSupplierDirectoryJPanel(userProcessContainer, supplierDirectory, userAccountDirectory);
        userProcessContainer.add("ManageSupplierDirectoryJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSupplierDirectoryActionPerformed

    private void btnManageMarketCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketCatalogueActionPerformed
        // TODO add your handling code here:
        ManageMarketJPanel panel = new ManageMarketJPanel(userProcessContainer, marketCatalog, marketOfferCatalog);
        userProcessContainer.add("ManageMarketJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMarketCatalogueActionPerformed

    private void btnReviewCompanyPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewCompanyPerformanceActionPerformed
        // TODO add your handling code here:
        CompanyPerformanceJPanel panel = new CompanyPerformanceJPanel(userProcessContainer, orderCatalog, marketOfferCatalog, supplierDirectory, salesPerson);
        userProcessContainer.add("CompanyPerformanceJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewCompanyPerformanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageMarketCatalogue;
    private javax.swing.JButton btnManagePersonDirectory;
    private javax.swing.JButton btnManageSupplierDirectory;
    private javax.swing.JButton btnReviewCompanyPerformance;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblAdministratorWorkArea;
    private javax.swing.JLabel lblSMAdminID;
    private javax.swing.JLabel lblSMAdminName;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtSMAdminID;
    private javax.swing.JTextField txtSMAdminName;
    // End of variables declaration//GEN-END:variables
}
