/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SMAdminInterface.ManageMarketCatalog;

import Business.Market.Market;
import Business.Market.MarketCatalog;
import Business.MarketOffers.MarketOffer;
import Business.MarketOffers.MarketOfferCatalog;
import Business.SupplierPackage.SupplierDirectory;
import Business.UserAccountPackage.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sachinsenthilkumar
 */
public class ManageMarketJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;
    UserAccountDirectory userAccountDirectory;
    Market market;
    MarketCatalog marketCatalog;
    MarketOfferCatalog marketOfferCatalog;
    /**
     * Creates new form ManageMarketJPanel
     */
    
  

    public ManageMarketJPanel(JPanel userProcessContainer, MarketCatalog marketCatalog, MarketOfferCatalog marketOfferCatalog) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.marketCatalog=marketCatalog;
        this.marketOfferCatalog = marketOfferCatalog;
        
       populateTable();
       
    }

    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel)tblMarketList.getModel();
        dtm.setRowCount(0);
        
        try{
        for(Market market : marketCatalog.getMarketList()){
            Object[] row = new Object[2];
            row[0] = market;
            row[1] = market.getMarketType();
            
            dtm.addRow(row);
        }
        }catch(Exception e){
            
        }
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageMarkets = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblMarketList = new javax.swing.JTable();
        btnSearchMarket = new javax.swing.JButton();
        btnAddMarket = new javax.swing.JButton();
        btnUpdateMarket = new javax.swing.JButton();
        btnDeleteMarket = new javax.swing.JButton();
        txtMarketID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        lblManageMarkets.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblManageMarkets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageMarkets.setText("Manage Markets - Work Responsibility");

        tblMarketList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market ID", "MarketType"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tblMarketList);

        btnSearchMarket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearchMarket.setText("Search Market");
        btnSearchMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMarketActionPerformed(evt);
            }
        });

        btnAddMarket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddMarket.setText("Add Market >>");
        btnAddMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarketActionPerformed(evt);
            }
        });

        btnUpdateMarket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdateMarket.setText("View/Update Market >>");
        btnUpdateMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMarketActionPerformed(evt);
            }
        });

        btnDeleteMarket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteMarket.setText("<< Delete Market >>");
        btnDeleteMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMarketActionPerformed(evt);
            }
        });

        txtMarketID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMarketID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMarketID.setText("Enter Market ID Here");
        txtMarketID.setToolTipText("Enter User Name");
        txtMarketID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMarketID.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        txtMarketID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMarketIDFocusGained(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManageMarkets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtMarketID, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAddMarket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchMarket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateMarket, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                .addComponent(btnDeleteMarket, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageMarkets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchMarket)
                    .addComponent(txtMarketID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddMarket)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateMarket)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteMarket)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMarketActionPerformed
        // TODO add your handling code here:
         if(txtMarketID.getText().equals("") || !(txtMarketID.getText().matches("[0-9A-Z]+"))){
            JOptionPane.showMessageDialog(null,"Invalid Data");
        }
        else{
            String id= txtMarketID.getText();
            Market market = marketCatalog.searchMarket(id);
        
            
            if(market == null){
                JOptionPane.showMessageDialog(null, "Market Does Not Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                for(MarketOffer marketOffer : marketOfferCatalog.getMarketOfferList()){
                    if(marketOffer.getMarket().getMarketId().compareTo(id)==0){
                        SearchUpdateMarketPanel panel = new SearchUpdateMarketPanel(userProcessContainer, market, marketOffer);
                        userProcessContainer.add("SearchUpdateMarketPanel", panel);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.next(userProcessContainer);

                        txtMarketID.setText("Enter Market ID Here");    
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSearchMarketActionPerformed

    private void btnAddMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarketActionPerformed
        // TODO add your handling code here:
        AddMarket panel = new AddMarket(userProcessContainer, supplierDirectory, marketCatalog, marketOfferCatalog);
        userProcessContainer.add("AddProductJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        System.out.println("Passed Market: "+market);
    }//GEN-LAST:event_btnAddMarketActionPerformed

    private void btnUpdateMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMarketActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMarketList.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE to View Details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Market market = (Market)tblMarketList.getValueAt(selectedRow, 0);
            for(MarketOffer marketOffer : marketOfferCatalog.getMarketOfferList()){
                if(marketOffer.getMarket().getMarketId().compareTo(market.getMarketId())==0){
                    SearchUpdateMarketPanel panel = new SearchUpdateMarketPanel(userProcessContainer, market, marketOffer);
                    userProcessContainer.add("SearchUpdateMarketPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                }
            }
        }
       
    }//GEN-LAST:event_btnUpdateMarketActionPerformed

    private void btnDeleteMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMarketActionPerformed
        // TODO add your handling code here:
          int row = tblMarketList.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE First", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to DELETE the Account?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            Market m = (Market)tblMarketList.getValueAt(row, 0);
            marketCatalog.deleteMarket(m);
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteMarketActionPerformed

    private void txtMarketIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMarketIDFocusGained
        // TODO add your handling code here:
        txtMarketID.setText("");
    }//GEN-LAST:event_txtMarketIDFocusGained

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMarket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteMarket;
    private javax.swing.JButton btnSearchMarket;
    private javax.swing.JButton btnUpdateMarket;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblManageMarkets;
    private javax.swing.JTable tblMarketList;
    private javax.swing.JTextField txtMarketID;
    // End of variables declaration//GEN-END:variables
}
