/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminInterface;

import Business.PersonPackage.PersonDirectory;
import Business.SupplierPackage.SupplierDirectory;
import Business.UserAccountPackage.UserAccount;
import Business.UserAccountPackage.UserAccountDirectory;
import UserInterface.SystemAdminInterface.ManageUserAccountsInterface.ManageUserAccountsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author eklav
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    UserAccount foundUserAccount;
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    UserAccountDirectory userAccountDirectory;
    SupplierDirectory supplierDirectory;

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(UserAccount foundUserAccount, JPanel userProcessContainer, PersonDirectory personDirectory, 
            UserAccountDirectory userAccountDirectory, SupplierDirectory supplierDirectory) {
        initComponents();
        this.foundUserAccount = foundUserAccount;
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.userAccountDirectory = userAccountDirectory;
        this.supplierDirectory = supplierDirectory;
        
        txtSystemAdminID.setText(String.valueOf(foundUserAccount.getUserID()));
        txtSystemAdminName.setText(foundUserAccount.getPerson().getFirstName()+" "+foundUserAccount.getPerson().getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblSystemAdminID = new javax.swing.JLabel();
        lblSystemAdminName = new javax.swing.JLabel();
        txtSystemAdminID = new javax.swing.JTextField();
        txtSystemAdminName = new javax.swing.JTextField();
        lblAdministratorWorkArea = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        btnManageUserAccounts = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setText("Welcome System Adminstrator");

        lblSystemAdminID.setText("System Adminstrator User ID:");

        lblSystemAdminName.setText("System Adminstrator Name:");

        txtSystemAdminID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSystemAdminID.setDisabledTextColor(new java.awt.Color(0, 0, 149));
        txtSystemAdminID.setEnabled(false);

        txtSystemAdminName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSystemAdminName.setDisabledTextColor(new java.awt.Color(0, 0, 149));
        txtSystemAdminName.setEnabled(false);

        lblAdministratorWorkArea.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblAdministratorWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministratorWorkArea.setText("System Adminstrator Work Area");

        btnManageUserAccounts.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnManageUserAccounts.setText("Manage User Accounts >>");
        btnManageUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountsActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAdministratorWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSystemAdminID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSystemAdminName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSystemAdminID)
                            .addComponent(txtSystemAdminName)))
                    .addComponent(btnManageUserAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addComponent(btnLogOut)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(btnLogOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSystemAdminID)
                    .addComponent(txtSystemAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSystemAdminName)
                    .addComponent(txtSystemAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAdministratorWorkArea)
                .addGap(18, 18, 18)
                .addComponent(btnManageUserAccounts)
                .addContainerGap(343, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountsActionPerformed
        // TODO add your handling code here:
        ManageUserAccountsJPanel panel = new ManageUserAccountsJPanel(userProcessContainer, personDirectory, userAccountDirectory, supplierDirectory);
        userProcessContainer.add("ManageUserAccountsJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageUserAccountsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageUserAccounts;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblAdministratorWorkArea;
    private javax.swing.JLabel lblSystemAdminID;
    private javax.swing.JLabel lblSystemAdminName;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtSystemAdminID;
    private javax.swing.JTextField txtSystemAdminName;
    // End of variables declaration//GEN-END:variables
}
