/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.Market.MarketCatalog;
import Business.MarketOffers.MarketOfferCatalog;
import Business.PersonPackage.PersonDirectory;
import Business.PersonPackage.SalesPerson;
import Business.Sales.OrderCatalog;
import Business.SupplierPackage.SupplierDirectory;
import Business.UserAccountPackage.UserAccountDirectory;
import java.awt.CardLayout;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eklav
 */
public class MainJFrame extends javax.swing.JFrame {
    
    PersonDirectory personDirectory;
    UserAccountDirectory userAccountDirectory;
    SupplierDirectory supplierDirectory;
    MarketOfferCatalog marketOfferCatalog;
    MarketCatalog marketCatalog;
    OrderCatalog orderCatalog;
    SalesPerson salespPerson;
            
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() throws UnsupportedEncodingException {
        initComponents();
        Business business = new Business();
        this.personDirectory = business.getPersonDirectory();
        this.userAccountDirectory = business.getUserAccountDirectory();
        this.supplierDirectory = business.getSupplierDirectory();
        this.marketCatalog = business.getMarketCatalog();
        this.marketOfferCatalog = business.getMarketOfferCatalog();
        this.orderCatalog = business.getOrderCatalog();
        this.salespPerson = business.getSalesPerson();
        
//        business.simulateSales(business, 100);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        jSeparator = new javax.swing.JSeparator();
        lblUserPersonMgmt = new javax.swing.JLabel();
        lblInterface = new javax.swing.JLabel();
        btnStartTheApplication = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblUserPersonMgmt.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblUserPersonMgmt.setForeground(new java.awt.Color(206, 0, 0));
        lblUserPersonMgmt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Logo.PNG"))); // NOI18N
        lblUserPersonMgmt.setText(" Sales");

        lblInterface.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInterface.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInterface.setText("since 1906");

        btnStartTheApplication.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnStartTheApplication.setText("Start the Application");
        btnStartTheApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartTheApplicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserPersonMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnStartTheApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblUserPersonMgmt)
                .addGap(1, 1, 1)
                .addComponent(lblInterface)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStartTheApplication)
                .addGap(33, 33, 33))
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartTheApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTheApplicationActionPerformed
        // TODO add your handling code here:
        LoginScreen loginScreen = new LoginScreen(userProcessContainer, personDirectory, userAccountDirectory, 
                supplierDirectory, marketOfferCatalog, marketCatalog, orderCatalog, salespPerson);
        userProcessContainer.add("LoginScreen", loginScreen);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStartTheApplicationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartTheApplication;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblInterface;
    private javax.swing.JLabel lblUserPersonMgmt;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
