/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.Schedule;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eklav
 */
public class ViewAirlinerProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerProfileJPanel
     */
    
    JPanel userProcessContainer;
    Airliner airliner;
    
    public ViewAirlinerProfileJPanel(JPanel userProcessContainer, Airliner airliner) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.airliner = airliner;
        
        populateAirlinerDetails();
        populateTable();
    }
    
    private void populateAirlinerDetails(){
        txtAirlinerID.setText(airliner.getAirlinerID());
        txtAirlinerName.setText(airliner.getAirlinerName());
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblFlights.getModel();
        dtm.setRowCount(0);
        
        for(Schedule schedule : airliner.getSchedules()){
            Object[] row = new Object[2];
            row[0] = schedule;
            row[1] = schedule.getAirplaneModelNo();
            
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAirlinersProfile = new javax.swing.JLabel();
        lblAirlinerID = new javax.swing.JLabel();
        lblAirlinerName = new javax.swing.JLabel();
        txtAirlinerID = new javax.swing.JTextField();
        txtAirlinerName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnViewFlightDetails = new javax.swing.JButton();
        txtSearchFlightNo = new javax.swing.JTextField();
        flightScrollPane = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();
        btnSearchFlightNo = new javax.swing.JButton();
        btnDeleteFlight = new javax.swing.JButton();
        btnAddNewFlight = new javax.swing.JButton();

        lblAirlinersProfile.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblAirlinersProfile.setText("Airliner's Profile");

        lblAirlinerID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAirlinerID.setText("Airliner ID:");

        lblAirlinerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAirlinerName.setText("Airliner Name:");

        txtAirlinerID.setBackground(new java.awt.Color(240, 240, 240));
        txtAirlinerID.setEnabled(false);

        txtAirlinerName.setBackground(new java.awt.Color(240, 240, 240));
        txtAirlinerName.setEnabled(false);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewFlightDetails.setText("View Flight Details");
        btnViewFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightDetailsActionPerformed(evt);
            }
        });

        txtSearchFlightNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFlightNoActionPerformed(evt);
            }
        });

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No", "Airplane Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flightScrollPane.setViewportView(tblFlights);
        if (tblFlights.getColumnModel().getColumnCount() > 0) {
            tblFlights.getColumnModel().getColumn(0).setResizable(false);
            tblFlights.getColumnModel().getColumn(1).setResizable(false);
        }

        btnSearchFlightNo.setText("Search & View Flight by No.");
        btnSearchFlightNo.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSearchFlightNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFlightNoActionPerformed(evt);
            }
        });

        btnDeleteFlight.setText("Delete");
        btnDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlightActionPerformed(evt);
            }
        });

        btnAddNewFlight.setText("Add New Flight");
        btnAddNewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtSearchFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchFlightNo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(flightScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAddNewFlight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewFlightDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(409, 409, 409)
                            .addComponent(btnDeleteFlight)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAirlinerID)
                                    .addComponent(lblAirlinerName))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAirlinerID)
                                    .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblAirlinersProfile))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAirlinersProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblAirlinerID)
                        .addGap(18, 18, 18)
                        .addComponent(lblAirlinerName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAirlinerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(flightScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchFlightNo)
                    .addComponent(txtSearchFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewFlightDetails)
                    .addComponent(btnDeleteFlight))
                .addGap(18, 18, 18)
                .addComponent(btnAddNewFlight)
                .addGap(80, 80, 80)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlights.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE to View Details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Schedule schedule = (Schedule)tblFlights.getValueAt(selectedRow, 0);
            ViewFlightsJPanel panel = new ViewFlightsJPanel(userProcessContainer, schedule);
            userProcessContainer.add("ViewFlightsJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewFlightDetailsActionPerformed

    private void btnSearchFlightNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFlightNoActionPerformed
        // TODO add your handling code here:
        if(txtSearchFlightNo.getText().equals("") || !(txtSearchFlightNo.getText().matches("[a-zA-Z0-9]+"))){
            JOptionPane.showMessageDialog(null,"Invalid Data");
        }
        else{
            Schedule result = airliner.searchFlight(txtSearchFlightNo.getText());
            if(result == null){
                JOptionPane.showMessageDialog(null, "Flight Number Does Not Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                ViewFlightsJPanel panel = new ViewFlightsJPanel(userProcessContainer, result);
                userProcessContainer.add("ViewFlightsJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                txtSearchFlightNo.setText("");
            }
        }
    }//GEN-LAST:event_btnSearchFlightNoActionPerformed

    private void btnAddNewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewFlightActionPerformed
        // TODO add your handling code here:
        AddFlightsJPanel panel = new AddFlightsJPanel(userProcessContainer, airliner);
        userProcessContainer.add("AddFlightsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddNewFlightActionPerformed

    private void btnDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlightActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlights.getSelectedRow();
        if(selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to DELETE the Flight?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Schedule schedule = (Schedule)tblFlights.getValueAt(selectedRow, 0);
                airliner.deleteFlight(schedule);
                
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteFlightActionPerformed

    private void txtSearchFlightNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFlightNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFlightNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewFlight;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteFlight;
    private javax.swing.JButton btnSearchFlightNo;
    private javax.swing.JButton btnViewFlightDetails;
    private javax.swing.JScrollPane flightScrollPane;
    private javax.swing.JLabel lblAirlinerID;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JLabel lblAirlinersProfile;
    private javax.swing.JTable tblFlights;
    private javax.swing.JTextField txtAirlinerID;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtSearchFlightNo;
    // End of variables declaration//GEN-END:variables
}
