/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ViewAgencyElement;

import Business.Airliner;
import Business.AirlinerCat;
import Business.Customer;
import Business.CustomerCat;
import Business.Schedule;
import java.time.Clock;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eklav
 */
public class ViewAgencyElementWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAgencyElementWorkAreaJPanel
     */
    JPanel userProcessContainer;
    AirlinerCat airlinerCat;
    CustomerCat customerCat;
    
    public ViewAgencyElementWorkAreaJPanel(JPanel userProcessContainer, AirlinerCat airlinerCat, CustomerCat customerCat) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.airlinerCat = airlinerCat;
        this.customerCat = customerCat;
        
        populateDropDowns();
        populateTable();
        populateCustomersTable();
        populateDropDowns();
    }
    
    public void populateDropDowns(){
        cmbSource.removeAllItems();
        ArrayList<String> sourceArray = new ArrayList<String>();
        sourceArray.add("Start");
        
        for(Airliner airliner : airlinerCat.getAirliners()){
            for(Schedule schedule : airliner.getSchedules()){
                String source = schedule.getSource();
                for(String s : sourceArray){
                    if((!s.equals(source))){
                        cmbSource.addItem(source);
                    }
                }
                sourceArray.add(source);
            }
        }
        System.out.print("Check"+sourceArray);
    }
    
    public void populateCustomersTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblCustomersTable.getModel();
        dtm.setRowCount(0);
        
        double revenue = 0;
        for(Customer customer : customerCat.getCustomers()){
            Object[] row = new Object[7];
            row[0] = customer;
            row[1] = customer.getFirstName();
            row[2] = customer.getLastName();
            row[3] = customer.geteMail();
            row[4] = customer.getPhoneNum();
            row[5] = customer.getSeatNum();
            row[6] = customer.getBookedSeatPrice();
            
            revenue += customer.getBookedSeatPrice();
            
            dtm.addRow(row);   
        }
        txtRevenueGenerated.setText(String.valueOf(revenue));
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblViewAgencyElements.getModel();
        dtm.setRowCount(0);
        
        for(Airliner airliner : airlinerCat.getAirliners()){
            for(Schedule schedule : airliner.getSchedules()){
            Object[] row = new Object[6];
            row[0] = schedule.getAirlinerID();
            row[1] = schedule;
            row[2] = schedule.getSource();
            row[3] = schedule.getDestination();
            row[4] = schedule.getTimeOfDay();
            row[5] = schedule.getSurgePricing();
            
            dtm.addRow(row);   
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TravelAgencyElementsJLabel = new javax.swing.JLabel();
        sourceJLabel = new javax.swing.JLabel();
        destinationJLabel = new javax.swing.JLabel();
        btnSearchFlights = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        tblViewAgencyElements = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomersTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRevenueGenerated = new javax.swing.JTextField();
        cmbSource = new javax.swing.JComboBox<>();

        TravelAgencyElementsJLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TravelAgencyElementsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TravelAgencyElementsJLabel.setText("Travel Agency's Elements");
        TravelAgencyElementsJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        sourceJLabel.setText("Source");

        destinationJLabel.setText("Destination");

        btnSearchFlights.setText("Search");
        btnSearchFlights.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSearchFlights.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFlightsActionPerformed(evt);
            }
        });

        tblViewAgencyElements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner ID", "Flight No.", "Source", "Destination", "Time Of Day", "Surge Pricing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(tblViewAgencyElements);
        if (tblViewAgencyElements.getColumnModel().getColumnCount() > 0) {
            tblViewAgencyElements.getColumnModel().getColumn(0).setResizable(false);
            tblViewAgencyElements.getColumnModel().getColumn(1).setResizable(false);
            tblViewAgencyElements.getColumnModel().getColumn(2).setResizable(false);
            tblViewAgencyElements.getColumnModel().getColumn(3).setResizable(false);
            tblViewAgencyElements.getColumnModel().getColumn(4).setResizable(false);
            tblViewAgencyElements.getColumnModel().getColumn(5).setResizable(false);
        }

        tblCustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerID", "FirstName", "LastName", "EMail", "PhoneNo", "SeatNo.", "Amount Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomersTable);
        if (tblCustomersTable.getColumnModel().getColumnCount() > 0) {
            tblCustomersTable.getColumnModel().getColumn(0).setResizable(false);
            tblCustomersTable.getColumnModel().getColumn(1).setResizable(false);
            tblCustomersTable.getColumnModel().getColumn(2).setResizable(false);
            tblCustomersTable.getColumnModel().getColumn(3).setResizable(false);
            tblCustomersTable.getColumnModel().getColumn(4).setResizable(false);
            tblCustomersTable.getColumnModel().getColumn(5).setResizable(false);
            tblCustomersTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Booked Customers");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Revenue Genrated");

        txtRevenueGenerated.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(txtRevenueGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(323, 323, 323)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sourceJLabel)
                                .addGap(27, 27, 27)
                                .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbSource, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btnSearchFlights)
                                .addGap(147, 147, 147)
                                .addComponent(destinationJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TravelAgencyElementsJLabel)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TravelAgencyElementsJLabel)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationJLabel)
                    .addComponent(sourceJLabel)
                    .addComponent(btnSearchFlights)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRevenueGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFlightsActionPerformed
        // TODO add your handling code here:
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        
        if((source.equals("") || !(source.matches("[a-zA-Z]+")))||
                (destination.equals("") || !(destination.matches("[a-zA-Z]+")))){
            
            JOptionPane.showMessageDialog(null,"Invalid Data");
        }
        else{
            DefaultTableModel dtm = (DefaultTableModel)tblViewAgencyElements.getModel();
            dtm.setRowCount(0);
        
            for(Airliner airliner : airlinerCat.getAirliners()){
                for(Schedule schedule : airliner.getSchedules()){
                    double surgePriceOfFlight = Double.parseDouble(schedule.getSurgePricing());
                    if((schedule.getSource().compareTo(source)==0)&&(schedule.getDestination().compareTo(destination)==0)){
                        Object[] row = new Object[6];
                        row[0] = schedule.getAirlinerID();
                        row[1] = schedule;
                        row[2] = schedule.getSource();
                        row[3] = schedule.getDestination();
                        row[4] = schedule.getTimeOfDay();
                        row[5] = schedule.getSurgePricing();

                        dtm.addRow(row);   
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSearchFlightsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TravelAgencyElementsJLabel;
    private javax.swing.JButton btnSearchFlights;
    private javax.swing.JComboBox<String> cmbSource;
    private javax.swing.JLabel destinationJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel sourceJLabel;
    private javax.swing.JTable tblCustomersTable;
    private javax.swing.JTable tblViewAgencyElements;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtRevenueGenerated;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
