/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InventoryClerk;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InventoryClerkOrganization;
import Business.Organization.PharmacistOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VaccinationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class InventoryClerkWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private InventoryClerkOrganization labOrganization;
    private Enterprise enterprise;
    private Network network;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public InventoryClerkWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise, Network network,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        this.labOrganization = (InventoryClerkOrganization)organization;
        this.network = network;
        populatenetworkTable();
        try{
            populatenetworkTable();
            
        }
        catch(Exception e){
            System.out.println("Network Request not there");
            
        }
        try{
            populateEcoRequests();
            
        }
        catch(Exception e){
            System.out.println("Network Reuest not there");
            
        }
        
    }
    public void populateEcoRequests() {
        DefaultTableModel model = (DefaultTableModel)ecoWorkRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : business.getWorkQueue().getWorkRequestList()){
            if(business.getEnterprise(request.getSender())!=enterprise){
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = request.getQuantity();
                String sender = business.getEnterprise(userAccount).getName()+","+business.getNetwork(userAccount);
                row[2] = sender;
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row[4] = request.getStatus();

                model.addRow(row);
            }
            
        }
    }
    
    public void populatenetworkTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : network.getWorkQueue().getWorkRequestList()){
            System.out.println("sender"+request.getSender().getUsername());
           // if(business.getEnterprise(request.getSender()).getEnterpriseType()!=Enterprise.EnterpriseType.SatelliteClinic){
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = request.getQuantity();
                String sender = business.getEnterprise(request.getSender()).getName()+","+business.getNetwork(request.getSender());
                row[2] = sender;
                System.out.println(row[1]);
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                if(business.getEnterprise(request.getReceiver())!=enterprise && request.getReceiver() != null){
                    String receiver = business.getEnterprise(request.getReceiver()).getName()+","+business.getNetwork(request.getReceiver());
                    row[3] = receiver;
                }
                else{
                    row[3] = request.getReceiver();
                }
                row[4] = request.getStatus();

                model.addRow(row);
            }
           
        //}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reqNetworkjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ecoWorkRequestJTable = new javax.swing.JTable();
        networkAssignJButton = new javax.swing.JButton();
        refreshJButton1 = new javax.swing.JButton();
        networkProcessJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 229, 229));

        workRequestJTable.setBackground(new java.awt.Color(255, 203, 203));
        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaccine", "Quantity", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        assignJButton.setBackground(new java.awt.Color(137, 255, 137));
        assignJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        processJButton.setBackground(new java.awt.Color(137, 255, 137));
        processJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setBackground(new java.awt.Color(137, 255, 137));
        refreshJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventory Clerk Work Area");

        reqNetworkjButton.setBackground(new java.awt.Color(137, 255, 137));
        reqNetworkjButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        reqNetworkjButton.setText("Request Eco System");
        reqNetworkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqNetworkjButtonActionPerformed(evt);
            }
        });

        ecoWorkRequestJTable.setBackground(new java.awt.Color(255, 203, 203));
        ecoWorkRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ecoWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaccine", "Quantity", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ecoWorkRequestJTable);
        if (ecoWorkRequestJTable.getColumnModel().getColumnCount() > 0) {
            ecoWorkRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            ecoWorkRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            ecoWorkRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            ecoWorkRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            ecoWorkRequestJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        networkAssignJButton.setBackground(new java.awt.Color(255, 138, 138));
        networkAssignJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        networkAssignJButton.setText("Assign to me");
        networkAssignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkAssignJButtonActionPerformed(evt);
            }
        });

        refreshJButton1.setBackground(new java.awt.Color(255, 138, 138));
        refreshJButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshJButton1.setText("Refresh");
        refreshJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton1ActionPerformed(evt);
            }
        });

        networkProcessJButton.setBackground(new java.awt.Color(255, 138, 138));
        networkProcessJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        networkProcessJButton.setText("Process");
        networkProcessJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkProcessJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vaccine Request from Network");

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vaccine Request from Ecosystem");

        backButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(networkAssignJButton)
                        .addGap(18, 18, 18)
                        .addComponent(refreshJButton1)
                        .addGap(18, 18, 18)
                        .addComponent(networkProcessJButton)
                        .addGap(383, 445, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignJButton)
                                .addGap(18, 18, 18)
                                .addComponent(refreshJButton)
                                .addGap(18, 18, 18)
                                .addComponent(processJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reqNetworkjButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJButton)
                    .addComponent(processJButton)
                    .addComponent(refreshJButton)
                    .addComponent(reqNetworkjButton))
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkAssignJButton)
                    .addComponent(networkProcessJButton)
                    .addComponent(refreshJButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        try{
            populatenetworkTable();
            
        }
        catch(Exception e){
            System.out.println("Network Request not there");
            
        }
        try{
            populateEcoRequests();
            
        }
        catch(Exception e){
            System.out.println("Network Reuest not there");
            
        }
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        VaccinationRequest request = (VaccinationRequest)workRequestJTable.getValueAt(selectedRow, 0);
     
        //request.setStatus("Processing");
        
        ProcessWorkRequestJPanel1 processWorkRequestJPanel = new ProcessWorkRequestJPanel1(userProcessContainer, request,business);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        try{
            populatenetworkTable();
            
        }
        catch(Exception e){
            System.out.println("Network Request not there");
            
        }
        try{
            populateEcoRequests();
            
        }
        catch(Exception e){
            System.out.println("Network Reuest not there");
            
        }
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void reqNetworkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqNetworkjButtonActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        VaccinationRequest request = (VaccinationRequest)workRequestJTable.getValueAt(selectedRow, 0);
     
        request.setStatus("Request Sent to EcoSystem");
        request.setSender(userAccount);
        business.getWorkQueue().addWorkRequest(request);
        try{
            populatenetworkTable();
            
        }
        catch(Exception e){
            System.out.println("Network Request not there");
            
        }
        try{
            populateEcoRequests();
            
        }
        catch(Exception e){
            System.out.println("Network Reuest not there");
            
        }
        
        
        
    }//GEN-LAST:event_reqNetworkjButtonActionPerformed

    private void networkAssignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkAssignJButtonActionPerformed
        int selectedRow = ecoWorkRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request = (WorkRequest)ecoWorkRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        try{
            populatenetworkTable();
            
        }
        catch(Exception e){
            System.out.println("Network Request not there");
            
        }
        try{
            populateEcoRequests();
            
        }
        catch(Exception e){
            System.out.println("Network Reuest not there");
            
        }
    }//GEN-LAST:event_networkAssignJButtonActionPerformed

    private void refreshJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshJButton1ActionPerformed

    private void networkProcessJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkProcessJButtonActionPerformed
         int selectedRow = ecoWorkRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        VaccinationRequest request = (VaccinationRequest)ecoWorkRequestJTable.getValueAt(selectedRow, 0);
     
        //request.setStatus("Processing");
        
        ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, request,business);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_networkProcessJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable ecoWorkRequestJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton networkAssignJButton;
    private javax.swing.JButton networkProcessJButton;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton refreshJButton1;
    private javax.swing.JButton reqNetworkjButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

    
}
