/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InventoryClerk;

import userinterface.Manufacture.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Inventory.InventoryDirectory;
import Business.Inventory.InventoryItem;
import userinterface.InventoryClerk.*;
import Business.WorkQueue.VaccinationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    VaccinationRequest request;
    EcoSystem business;
    InventoryDirectory cart;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, VaccinationRequest request, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.business= business;
        this.cart = new InventoryDirectory();
        if(this.request.getTansactionStatus()>1){
            acceptPurchaseOrderjButton.setVisible(false);
            denyPurchaseOrderJButton.setVisible(false);
        }
        enterprisejTextField.setText(business.getEnterprise(request.getSender()).getName());
        quantityrequiredjTextField.setText(String.valueOf(request.getQuantity()));
        vaccinerequiredjTextField.setText(String.valueOf(request.getVaccination().getName()));
        
        populateAvailabletable();
        try{
            populateAvailableCarttable();
        }
        catch(Exception e){
            
        }
    }
    public void populateAvailabletable(){
       
    }
    public void populateAvailableCarttable(){
        DefaultTableModel model = (DefaultTableModel)inverntoryCartJTable.getModel();
        Enterprise ent = business.getEnterprise(business.getCurrentUser());
        model.setRowCount(0);
        double price = 0;
        for(InventoryItem items : request.getCart().getInventoryDirectory()){
                Object[] row = new Object[8];
                row[0] = items;
                row[1] = items.getVacination().getName();
                row[2] = items.getVacination().getManufacturingDate();
                row[3] = items.getVacination().getExpiryDate();
                row[4] = items.getVacination().getBatchNo();
                row[5] = items.getQuantity();
                row[6] = items.getPrice();
                row[7] = items.getPrice()*items.getQuantity();
                price += items.getPrice()*items.getQuantity();
                model.addRow(row);
                
        }
        totaljTextField.setText(String.valueOf(price));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        denyPurchaseOrderJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vaccinerequiredjTextField = new javax.swing.JTextField();
        quantityrequiredjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enterprisejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inverntoryCartJTable = new javax.swing.JTable();
        acceptPurchaseOrderjButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        totaljTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 229, 229));
        setForeground(new java.awt.Color(255, 255, 255));

        denyPurchaseOrderJButton.setBackground(new java.awt.Color(255, 138, 138));
        denyPurchaseOrderJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        denyPurchaseOrderJButton.setText("Deny Purchase Order");
        denyPurchaseOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyPurchaseOrderJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Process Vaccine Request");

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Vaccine Required:");

        vaccinerequiredjTextField.setEditable(false);
        vaccinerequiredjTextField.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        vaccinerequiredjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinerequiredjTextFieldActionPerformed(evt);
            }
        });

        quantityrequiredjTextField.setEditable(false);
        quantityrequiredjTextField.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Quantity Required:");

        enterprisejTextField.setEditable(false);
        enterprisejTextField.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        enterprisejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisejTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Manufacturing :");

        inverntoryCartJTable.setBackground(new java.awt.Color(255, 203, 203));
        inverntoryCartJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inverntoryCartJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vaccine Id", "Vaccine Name", "Manufacturign Date", "Expiry Date", "Batch Number", "Quantity", "Cost Per tiem", "Total Item cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(inverntoryCartJTable);

        acceptPurchaseOrderjButton.setBackground(new java.awt.Color(255, 138, 138));
        acceptPurchaseOrderjButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acceptPurchaseOrderjButton.setText("Accept Purchase Order");
        acceptPurchaseOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptPurchaseOrderjButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Total Selling Price : ");

        totaljTextField.setEditable(false);
        totaljTextField.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Cart:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterprisejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vaccinerequiredjTextField)
                            .addComponent(quantityrequiredjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backJButton)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(denyPurchaseOrderJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acceptPurchaseOrderjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(vaccinerequiredjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quantityrequiredjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(enterprisejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptPurchaseOrderjButton)
                    .addComponent(jLabel7)
                    .addComponent(totaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(denyPurchaseOrderJButton))
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void denyPurchaseOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyPurchaseOrderJButtonActionPerformed
         int dialogueButton = JOptionPane.YES_NO_OPTION;
        int dialogueResult = JOptionPane.showConfirmDialog(null, "Are u sure you want to Deny the transaction?", "Alert : Non revertable", dialogueButton);
        if(dialogueResult == JOptionPane.YES_OPTION){
       request.setTansactionStatus(2);
       request.setStatus("Transaction Denied");
       JOptionPane.showMessageDialog(null, "You have denied this order");
       userProcessContainer.remove(this);
        }else{
            return;
        }
    }//GEN-LAST:event_denyPurchaseOrderJButtonActionPerformed

    private void vaccinerequiredjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinerequiredjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinerequiredjTextFieldActionPerformed

    private void enterprisejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterprisejTextFieldActionPerformed

    private void acceptPurchaseOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptPurchaseOrderjButtonActionPerformed
        int dialogueButton = JOptionPane.YES_NO_OPTION;
        int dialogueResult = JOptionPane.showConfirmDialog(null, "Are u sure you want to accept the transaction?", "Alert : Non revertable", dialogueButton);
        if(dialogueResult == JOptionPane.YES_OPTION){
             request.setTansactionStatus(3);
             request.setStatus("Accepted the order");
            Enterprise ent = business.getEnterprise(business.getCurrentUser());
            Enterprise ent2 = business.getEnterprise(request.getReceiver());
            for(InventoryItem item : request.getCart().getInventoryDirectory()){
                ent.getInventoryDirectory().getInventoryDirectory().add(item);
                for(InventoryItem item2 : ent2.getInventoryDirectory().getInventoryDirectory()){
                    if(item.getVacination().getBatchNo().equals(item2.getVacination().getBatchNo())){
                        item2.setQuantity(item2.getQuantity()-item.getQuantity());
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "items added to the enterprises inventory");
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }else{
            return;
        }
       
    }//GEN-LAST:event_acceptPurchaseOrderjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptPurchaseOrderjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton denyPurchaseOrderJButton;
    private javax.swing.JTextField enterprisejTextField;
    private javax.swing.JTable inverntoryCartJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField quantityrequiredjTextField;
    private javax.swing.JTextField totaljTextField;
    private javax.swing.JTextField vaccinerequiredjTextField;
    // End of variables declaration//GEN-END:variables
}
