/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SMAdminInterface.ManageSupplierDirectoryInterface;

import Business.SupplierPackage.Supplier;
import Business.SupplierPackage.SupplierDirectory;
import Business.UserAccountPackage.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eklav
 */
public class ManageSupplierDirectoryJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;
    UserAccountDirectory userAccountDirectory;

    /** Creates new form ManagePersonDirectoryJPanel */
    public ManageSupplierDirectoryJPanel(JPanel userProcessContainer, SupplierDirectory supplierDirectory, 
            UserAccountDirectory userAccountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        this.userAccountDirectory = userAccountDirectory;
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblSupplierList.getModel();
        dtm.setRowCount(0);
        
        for(Supplier supplier : supplierDirectory.getSupplierlist()){
            Object[] row = new Object[2];
            row[0] = supplier;
            row[1] = supplier.getSupplierName();
            
            dtm.addRow(row);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdateSupplierDetails = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        lblManageSupplierDirectory = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblSupplierList = new javax.swing.JTable();
        txtSearchSupplierID = new javax.swing.JTextField();
        btnSearchSupplier = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        btnUpdateSupplierDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdateSupplierDetails.setText("View/Update Supplier Details >>");
        btnUpdateSupplierDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSupplierDetailsActionPerformed(evt);
            }
        });

        btnDeleteSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteSupplier.setText("<< Delete the Supplier >>");
        btnDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplierActionPerformed(evt);
            }
        });

        lblManageSupplierDirectory.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblManageSupplierDirectory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageSupplierDirectory.setText("Manage Supplier Directory - Work Responsibility");

        tblSupplierList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tblSupplierList);
        if (tblSupplierList.getColumnModel().getColumnCount() > 0) {
            tblSupplierList.getColumnModel().getColumn(0).setResizable(false);
            tblSupplierList.getColumnModel().getColumn(1).setResizable(false);
        }

        txtSearchSupplierID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearchSupplierID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchSupplierID.setText("Enter Supplier ID Here");
        txtSearchSupplierID.setToolTipText("Enter Person ID");
        txtSearchSupplierID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearchSupplierID.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        txtSearchSupplierID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchSupplierIDFocusGained(evt);
            }
        });
        txtSearchSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSupplierIDActionPerformed(evt);
            }
        });

        btnSearchSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearchSupplier.setText("Search Supplier >>");
        btnSearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSupplierActionPerformed(evt);
            }
        });

        btnAddSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddSupplier.setText("Add New Supplier >>");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManageSupplierDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAddSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearchSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateSupplierDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblManageSupplierDirectory)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchSupplier)
                    .addComponent(txtSearchSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddSupplier)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateSupplierDetails)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteSupplier)
                .addGap(37, 37, 37)
                .addComponent(btnBack)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchSupplierIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchSupplierIDFocusGained
        // TODO add your handling code here:
        txtSearchSupplierID.setText("");
    }//GEN-LAST:event_txtSearchSupplierIDFocusGained

    private void btnSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSupplierActionPerformed
        // TODO add your handling code here:
        if(txtSearchSupplierID.getText().equals("") || !(txtSearchSupplierID.getText().matches("[0-9A-Z]+"))){
            JOptionPane.showMessageDialog(null,"Invalid Data");
        }
        else{
            Supplier result = supplierDirectory.searchSupplier(txtSearchSupplierID.getText());
            if(result == null){
                JOptionPane.showMessageDialog(null, "Supplier ID Does Not Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                SearchUpdateSupplierJPanel panel = new SearchUpdateSupplierJPanel(userProcessContainer, result, userAccountDirectory);
                userProcessContainer.add("SearchUpdateSupplierJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                
                txtSearchSupplierID.setText("Enter Supplier ID Here");
            }
        }
    }//GEN-LAST:event_btnSearchSupplierActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSupplierIDActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        // TODO add your handling code here:
        AddSupplierJPanel panel = new AddSupplierJPanel(userProcessContainer, supplierDirectory);
        userProcessContainer.add("AddSupplierJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnUpdateSupplierDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupplierDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSupplierList.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE to View Details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Supplier result = (Supplier)tblSupplierList.getValueAt(selectedRow, 0);
            SearchUpdateSupplierJPanel panel = new SearchUpdateSupplierJPanel(userProcessContainer, result, userAccountDirectory);
            userProcessContainer.add("SearchUpdatePersonJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnUpdateSupplierDetailsActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSupplierList.getSelectedRow();
        if(selectedRow >= 0){
            Supplier supplier = (Supplier)tblSupplierList.getValueAt(selectedRow, 0);
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to DELETE the Supplier?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                supplierDirectory.removeSupplier(supplier);
                populateTable();
            }           
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnSearchSupplier;
    private javax.swing.JButton btnUpdateSupplierDetails;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblManageSupplierDirectory;
    private javax.swing.JTable tblSupplierList;
    private javax.swing.JTextField txtSearchSupplierID;
    // End of variables declaration//GEN-END:variables

}
