/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRAdminInterface;

import Business.PersonDirectory;
import Business.UserAccount;
import Business.UserAccountDirectory;
import UserInterface.HRAdminInterface.ManagePersonDirectoryInterface.ManagePersonDirectoryJPanel;
import UserInterface.SystemAdminInterface.ManageUserAccountsInterface.ManageUserAccountsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author eklav
 */
public class HRAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    UserAccount foundUserAccount;
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    UserAccountDirectory userAccountDirectory;

    /**
     * Creates new form HRAdminWorkAreaJPanel
     */
    public HRAdminWorkAreaJPanel(UserAccount foundUserAccount, JPanel userProcessContainer, PersonDirectory personDirectory, UserAccountDirectory userAccountDirectory) {
        initComponents();
        this.foundUserAccount = foundUserAccount;
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.userAccountDirectory = userAccountDirectory;
        
        txtHRAdminID.setText(String.valueOf(foundUserAccount.getUserID()));
        txtHRAdminName.setText(foundUserAccount.getPerson().getFirstName()+" "+foundUserAccount.getPerson().getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManagePersonDirectory = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblHRAdminID = new javax.swing.JLabel();
        lblHRAdminName = new javax.swing.JLabel();
        txtHRAdminID = new javax.swing.JTextField();
        txtHRAdminName = new javax.swing.JTextField();
        btnLogOut = new javax.swing.JButton();
        lblAdministratorWorkArea = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();

        btnManagePersonDirectory.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnManagePersonDirectory.setText("Manage Person Directory >>");
        btnManagePersonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonDirectoryActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome HR Adminstrator");

        lblHRAdminID.setText("HR Adminstrator User ID:");

        lblHRAdminName.setText("HR Adminstrator Name:");

        txtHRAdminID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtHRAdminID.setDisabledTextColor(new java.awt.Color(0, 0, 149));
        txtHRAdminID.setEnabled(false);

        txtHRAdminName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtHRAdminName.setDisabledTextColor(new java.awt.Color(0, 0, 149));
        txtHRAdminName.setEnabled(false);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblAdministratorWorkArea.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblAdministratorWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministratorWorkArea.setText("HR Adminstrator Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(lblAdministratorWorkArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHRAdminID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHRAdminName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHRAdminID)
                            .addComponent(txtHRAdminName)))
                    .addComponent(btnManagePersonDirectory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addComponent(btnLogOut)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(lblWelcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHRAdminID)
                    .addComponent(txtHRAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHRAdminName)
                    .addComponent(txtHRAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAdministratorWorkArea)
                .addGap(18, 18, 18)
                .addComponent(btnManagePersonDirectory)
                .addContainerGap(343, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePersonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonDirectoryActionPerformed
        // TODO add your handling code here:
        ManagePersonDirectoryJPanel panel = new ManagePersonDirectoryJPanel(userProcessContainer, personDirectory, userAccountDirectory);
        userProcessContainer.add("ManageUserAccountsJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePersonDirectoryActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManagePersonDirectory;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblAdministratorWorkArea;
    private javax.swing.JLabel lblHRAdminID;
    private javax.swing.JLabel lblHRAdminName;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtHRAdminID;
    private javax.swing.JTextField txtHRAdminName;
    // End of variables declaration//GEN-END:variables
}
