/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SMAdminInterface.CompanyPerformanceInterface;

import Business.MarketOffers.MarketOfferCatalog;
import Business.PersonPackage.SalesPerson;
import Business.Sales.OrderCatalog;
import Business.SupplierPackage.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author eklav
 */
public class CompanyPerformanceJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    OrderCatalog orderCatalog;
    
    MarketOfferCatalog marketOfferCatalog; 
    SupplierDirectory supplierDirectory;
    
    SalesPerson salesPerson;

    /**
     * Creates new form CompanyPerformanceJPanel
     */
    public CompanyPerformanceJPanel(JPanel userProcessContainer, OrderCatalog orderCatalog,
            MarketOfferCatalog marketOfferCatalog, SupplierDirectory supplierDirectory, SalesPerson salesPerson) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.orderCatalog = orderCatalog;
        
        this.marketOfferCatalog = marketOfferCatalog;
        this.supplierDirectory = supplierDirectory;
        
        this.salesPerson = salesPerson;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageMarkets = new javax.swing.JLabel();
        btnTotalRevenueGenerated = new javax.swing.JButton();
        btnProductSalesRevenue = new javax.swing.JButton();
        btnSalesPersonPerformanceReview = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblManageMarkets.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblManageMarkets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageMarkets.setText("Company's Performance Review");

        btnTotalRevenueGenerated.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTotalRevenueGenerated.setText("Total Revenue Genrated >>");
        btnTotalRevenueGenerated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalRevenueGeneratedActionPerformed(evt);
            }
        });

        btnProductSalesRevenue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProductSalesRevenue.setText("Product Sales Performance >>");
        btnProductSalesRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductSalesRevenueActionPerformed(evt);
            }
        });

        btnSalesPersonPerformanceReview.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalesPersonPerformanceReview.setText("Sales Person Performance Review >>");
        btnSalesPersonPerformanceReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesPersonPerformanceReviewActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblManageMarkets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTotalRevenueGenerated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProductSalesRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalesPersonPerformanceReview, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageMarkets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTotalRevenueGenerated)
                .addGap(18, 18, 18)
                .addComponent(btnProductSalesRevenue)
                .addGap(18, 18, 18)
                .addComponent(btnSalesPersonPerformanceReview)
                .addGap(343, 343, 343)
                .addComponent(btnBack)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalRevenueGeneratedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalRevenueGeneratedActionPerformed
        // TODO add your handling code here:
        TotalRevenueGeneratedJPanel panel = new TotalRevenueGeneratedJPanel(userProcessContainer, orderCatalog);
        userProcessContainer.add("TotalRevenueGeneratedJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTotalRevenueGeneratedActionPerformed

    private void btnProductSalesRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductSalesRevenueActionPerformed
        // TODO add your handling code here:
        ProductSalesRevenueJPanel panel = new ProductSalesRevenueJPanel(userProcessContainer, orderCatalog,
                marketOfferCatalog, supplierDirectory);
        userProcessContainer.add("ProductSalesRevenueJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProductSalesRevenueActionPerformed

    private void btnSalesPersonPerformanceReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesPersonPerformanceReviewActionPerformed
        // TODO add your handling code here:
        SalesPersonPerformanceJPanel panel = new SalesPersonPerformanceJPanel(userProcessContainer, orderCatalog, salesPerson);
        userProcessContainer.add("SalesPersonPerformanceJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        System.out.println("Checking Size"+orderCatalog.getOrderList().size());
    }//GEN-LAST:event_btnSalesPersonPerformanceReviewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProductSalesRevenue;
    private javax.swing.JButton btnSalesPersonPerformanceReview;
    private javax.swing.JButton btnTotalRevenueGenerated;
    private javax.swing.JLabel lblManageMarkets;
    // End of variables declaration//GEN-END:variables
}
