/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DiseasesDrugs.Diseases;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.DiseasesDrugs.Vaccination;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sreer
 */
public class ManageVaccinationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccinationsJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    public ManageVaccinationsJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTable();
    }
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) vaccinationjTable.getModel();
        int sno = 1;
        model.setRowCount(0);
        try{
            for (Vaccination vac: system.getVaccinationDirectory().getvaccinationDirectory()) {
                        Object[] row = new Object[3];
                        row[0] = sno++;
                        row[1] = vac;
                        model.addRow(row);
            }
        }
            
        catch(Exception e){
                System.out.println("No data in table");
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccinationjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        addjButton = new javax.swing.JButton();
        vaccinationjTextField = new javax.swing.JTextField();
        manageSchedulejButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 229, 229));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Vaccinations Menu");

        vaccinationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S No.", "Vaccination Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccinationjTable);
        if (vaccinationjTable.getColumnModel().getColumnCount() > 0) {
            vaccinationjTable.getColumnModel().getColumn(0).setResizable(false);
            vaccinationjTable.getColumnModel().getColumn(1).setResizable(false);
        }

        backjButton.setBackground(new java.awt.Color(203, 203, 255));
        backjButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        deletejButton.setBackground(new java.awt.Color(255, 138, 138));
        deletejButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deletejButton.setText("Select & Delete Vaccine");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        addjButton.setBackground(new java.awt.Color(137, 255, 137));
        addjButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addjButton.setText("Add New Vaccine");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        vaccinationjTextField.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N

        manageSchedulejButton.setBackground(new java.awt.Color(137, 255, 137));
        manageSchedulejButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageSchedulejButton.setText("Manage Schedule");
        manageSchedulejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSchedulejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaccinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addjButton))
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deletejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageSchedulejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletejButton)
                    .addComponent(vaccinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageSchedulejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(backjButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        String name = vaccinationjTextField.getText();
        if (name.isEmpty()) {                                                           // if selectedRow <0 means the row is not selected
            JOptionPane.showMessageDialog(null, "please Insert name into Name Field", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         if((name.equals("") || !(name.matches("[a-zA-Z]+")))){
                
                JOptionPane.showMessageDialog(null,"invalid data,it must in alphabets");
            }
         else{
        Vaccination vac = system.getVaccinationDirectory().addVaccination();
        vac.setName(name);}
        populateTable();
    }//GEN-LAST:event_addjButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        int selectRow=(Integer)vaccinationjTable.getSelectedRow();
        if (selectRow < 0) {                                                           // if selectedRow <0 means the row is not selected
            JOptionPane.showMessageDialog(null, "please select any row from the first table", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Vaccination v = (Vaccination) vaccinationjTable.getValueAt(selectRow, 1);
        system.getVaccinationDirectory().deleteVaccination(v);
        populateTable();
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        UserInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel sysAdminwjp = (UserInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backjButtonActionPerformed

    private void manageSchedulejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSchedulejButtonActionPerformed
        int selectRow=(Integer)vaccinationjTable.getSelectedRow();
        if (selectRow < 0) {                                                           // if selectedRow <0 means the row is not selected
            JOptionPane.showMessageDialog(null, "please select any row from the first table", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Vaccination dis = (Vaccination) vaccinationjTable.getValueAt(selectRow, 1);
        ManageScheduleIntervalsJPanel manageDiseasesVaccinationsJPanel = new ManageScheduleIntervalsJPanel(userProcessContainer, system,dis);
        userProcessContainer.add("ManageDiseasesVaccinationsJPanel", manageDiseasesVaccinationsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSchedulejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageSchedulejButton;
    private javax.swing.JTable vaccinationjTable;
    private javax.swing.JTextField vaccinationjTextField;
    // End of variables declaration//GEN-END:variables
}
