package UserInterface.ManageCustomers;

import Business.Customer;
import Business.CustomerCat;
import Business.Schedule;
import Business.Seat;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eklav
 */
public class BookCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookCustomerJPanel
     */
    
    JPanel userProcessContainer;
    Schedule schedule;
    CustomerCat customerCat;
    
    public BookCustomerJPanel(JPanel userProcessContainer, Schedule schedule, CustomerCat customerCat) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.schedule = schedule;
        this.customerCat = customerCat;
        
        populateFlightDetails();
        
        populateTable();
    }
    
    private void populateFlightDetails(){
        txtAirlinerID.setText(schedule.getAirlinerID());
        txtAirplaneModelNo.setText(schedule.getAirplaneModelNo());
        txtDestination.setText(schedule.getDestination());
        txtFlightNo.setText(schedule.getFlightNo());
        txtSource.setText(schedule.getSource());
        txtTimeOfDay.setText(schedule.getTimeOfDay());
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblSeats.getModel();
        dtm.setRowCount(0);
        
        for(Seat seat : schedule.getSeats()){
            if(seat.getCustomerID() == null){
                Object[] row = new Object[2];
                row[0] = seat;
                row[1] = seat.getSeatPrice();

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBestDeals = new javax.swing.JLabel();
        lblFlightDetails = new javax.swing.JLabel();
        lblAirliner = new javax.swing.JLabel();
        lblFlightNo = new javax.swing.JLabel();
        lblAirplaneModelNo = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblTimeOfDay = new javax.swing.JLabel();
        txtAirlinerID = new javax.swing.JTextField();
        txtFlightNo = new javax.swing.JTextField();
        txtAirplaneModelNo = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtTimeOfDay = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSeats = new javax.swing.JTable();
        lblFlightDetails2 = new javax.swing.JLabel();
        lblFlightDetails3 = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblSeatNumber = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtSeatNumber = new javax.swing.JTextField();
        btnBookTheFlight = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAddSeat = new javax.swing.JButton();

        lblBestDeals.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblBestDeals.setText("Booking Page & Seat Confirmation");

        lblFlightDetails.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblFlightDetails.setText("Flight Details");

        lblAirliner.setText("Airliner");

        lblFlightNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFlightNo.setText("Flight No.:");

        lblAirplaneModelNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAirplaneModelNo.setText("Airplane Model No.:");

        lblSource.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSource.setText("Source:");

        lblDestination.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDestination.setText("Destination:");

        lblTimeOfDay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTimeOfDay.setText("Time of Day:");

        txtAirlinerID.setEnabled(false);

        txtFlightNo.setEnabled(false);

        txtAirplaneModelNo.setEnabled(false);

        txtSource.setEnabled(false);

        txtDestination.setEnabled(false);

        txtTimeOfDay.setEnabled(false);

        tblSeats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat Number", "Seat Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSeats);
        if (tblSeats.getColumnModel().getColumnCount() > 0) {
            tblSeats.getColumnModel().getColumn(0).setResizable(false);
            tblSeats.getColumnModel().getColumn(1).setResizable(false);
        }

        lblFlightDetails2.setText("Seats Available in the Flight");

        lblFlightDetails3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblFlightDetails3.setText("Customer Details");

        lblCustomerID.setText("CustomerID:");

        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName.setText("First Name:");

        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLastName.setText("Last Name:");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail.setText("Email:");

        lblPhoneNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhoneNo.setText("Phone No.:");

        lblSeatNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSeatNumber.setText("Seat Number:");

        txtSeatNumber.setEnabled(false);

        btnBookTheFlight.setText("Book the Flight");
        btnBookTheFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTheFlightActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddSeat.setText("Select & Add Seat");
        btnAddSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblFlightDetails2)
                            .addGap(495, 495, 495))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTimeOfDay)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTimeOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDestination)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblSource)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAirplaneModelNo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAirplaneModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblFlightNo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAirliner)
                                            .addGap(136, 136, 136)
                                            .addComponent(txtAirlinerID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGap(135, 135, 135))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(104, 104, 104)
                                    .addComponent(btnAddSeat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCustomerID)
                                        .addComponent(lblFirstName)
                                        .addComponent(lblLastName)
                                        .addComponent(lblEmail)
                                        .addComponent(lblPhoneNo)
                                        .addComponent(lblSeatNumber))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnBookTheFlight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(lblBestDeals))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFlightDetails)
                .addGap(327, 327, 327)
                .addComponent(lblFlightDetails3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBestDeals)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightDetails)
                    .addComponent(lblFlightDetails3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerID)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNo)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeatNumber)
                            .addComponent(txtSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAirliner)
                            .addComponent(txtAirlinerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFlightNo)
                            .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAirplaneModelNo)
                            .addComponent(txtAirplaneModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSource)
                            .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDestination)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTimeOfDay)
                            .addComponent(txtTimeOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFlightDetails2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBookTheFlight))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAddSeat))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookTheFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTheFlightActionPerformed
        // TODO add your handling code here:
        String customerID = txtCustomerID.getText();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String eMail = txtEmail.getText();
        String phoneNum = txtPhoneNo.getText();
        String seatNum = txtSeatNumber.getText();
        
        if((customerID.equals("") || !(customerID.matches("[a-zA-Z0-9]+")))||
                (firstName.equals("") || !(firstName.matches("[a-zA-Z]+")))||
                (lastName.equals("") || !(lastName.matches("[a-zA-Z0-9]+")))||
                (eMail.equals("") || !(eMail.matches("[a-zA-Z0-9@.]+")))||
                (phoneNum.equals("") || !(phoneNum.matches("[0-9]+")))||
                (seatNum.equals("") || !(seatNum.matches("[a-zA-Z0-9]+")))){
            JOptionPane.showMessageDialog(null,"Invalid Data");
        }
        else{
            Customer customer = customerCat.addCustomer();
            customer.setCustomerID(customerID);
            customer.setFirstName(firstName);
            customer.setLastName(lastName);
            customer.setPhoneNum(phoneNum);
            customer.setSeatNum(seatNum);
            customer.seteMail(eMail);
            
            for(Seat s: schedule.getSeats()){
                if(seatNum.compareTo(s.getSeatNum())==0){
                    s.setCustomerID(customerID);
                    customer.setBookedSeatPrice(s.getSeatPrice());
                }
            }
            int i=1;
            for(Seat a : schedule.getSeats()){
                System.out.println(i+":SeatNum-->"+a.getSeatNum()+"\tSeatPrice-->"+a.getSeatPrice()+"\tCustomerID-->"+a.getCustomerID());
                i++;
            }
            
            JOptionPane.showMessageDialog(null, "Flight No: " + txtFlightNo.getText() + " with Seat No " 
                    + txtSeatNumber.getText() +" booked successfully. Please take a screenshot");
            
            txtCustomerID.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtEmail.setText("");
            txtPhoneNo.setText("");
            txtSeatNumber.setText("");
            
            populateTable();
        }
    }//GEN-LAST:event_btnBookTheFlightActionPerformed

    private void btnAddSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSeatActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSeats.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE to View Details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Seat seat = (Seat)tblSeats.getValueAt(selectedRow, 0);
            txtSeatNumber.setText(seat.getSeatNum());
        }
    }//GEN-LAST:event_btnAddSeatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSeat;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookTheFlight;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAirliner;
    private javax.swing.JLabel lblAirplaneModelNo;
    private javax.swing.JLabel lblBestDeals;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFlightDetails;
    private javax.swing.JLabel lblFlightDetails2;
    private javax.swing.JLabel lblFlightDetails3;
    private javax.swing.JLabel lblFlightNo;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblSeatNumber;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTimeOfDay;
    private javax.swing.JTable tblSeats;
    private javax.swing.JTextField txtAirlinerID;
    private javax.swing.JTextField txtAirplaneModelNo;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFlightNo;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSeatNumber;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTimeOfDay;
    // End of variables declaration//GEN-END:variables
}
