/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Airliner;
import Business.AirlinerCat;
import Business.CustomerCat;
import Business.Schedule;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eklav
 */
public class ManageCustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    AirlinerCat airlinerCat;
    CustomerCat customerCat;
    
    public ManageCustomerWorkAreaJPanel(JPanel userProcessContainer, AirlinerCat airlinerCat, CustomerCat customerCat) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.airlinerCat = airlinerCat;
        this.customerCat = customerCat;
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblBestDealFlight.getModel();
        dtm.setRowCount(0);
        
        for(Airliner airliner : airlinerCat.getAirliners()){
            for(Schedule schedule : airliner.getSchedules()){
            Object[] row = new Object[4];
            row[0] = schedule;
            row[1] = schedule.getSource();
            row[2] = schedule.getDestination();
            row[3] = schedule.getSurgePricing();
            
            dtm.addRow(row);   
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBestDeals = new javax.swing.JLabel();
        txtsurgePricing = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        lblDestination = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        btnSearchFlight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBestDealFlight = new javax.swing.JTable();
        btnSelectAndBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        lblBestDeals.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblBestDeals.setText("Best Deals Available for Customers");

        lblPrice.setText("Max. Surge Price*:");

        lblSource.setText("Source:");

        lblDestination.setText("Destination:");

        btnSearchFlight.setText("Search");
        btnSearchFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFlightActionPerformed(evt);
            }
        });

        tblBestDealFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No.", "Source", "Destination", "Airliner Surge Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBestDealFlight);
        if (tblBestDealFlight.getColumnModel().getColumnCount() > 0) {
            tblBestDealFlight.getColumnModel().getColumn(0).setResizable(false);
            tblBestDealFlight.getColumnModel().getColumn(1).setResizable(false);
            tblBestDealFlight.getColumnModel().getColumn(2).setResizable(false);
            tblBestDealFlight.getColumnModel().getColumn(3).setResizable(false);
        }

        btnSelectAndBook.setText("Select & Book Seat");
        btnSelectAndBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAndBookActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("*Our Base price for Window Seats is $40, for Middle Seats \nis $20 and for Aisle Seats is $50.\nSurge Price is an additional charge on the mentioned seats\nto accomodate Convenience Charges.");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSelectAndBook, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblBestDeals))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(lblSource)
                            .addComponent(lblDestination))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDestination)
                            .addComponent(txtSource)
                            .addComponent(txtsurgePricing)
                            .addComponent(btnSearchFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBestDeals)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtsurgePricing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrice)
                        .addGap(11, 11, 11)
                        .addComponent(lblSource)
                        .addGap(11, 11, 11)
                        .addComponent(lblDestination)))
                .addGap(18, 18, 18)
                .addComponent(btnSearchFlight)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnSelectAndBook)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectAndBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAndBookActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBestDealFlight.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE to View Details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Schedule schedule = (Schedule)tblBestDealFlight.getValueAt(selectedRow, 0);
            BookCustomerJPanel panel = new BookCustomerJPanel(userProcessContainer, schedule, customerCat);
            userProcessContainer.add("BookCustomerJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnSelectAndBookActionPerformed

    private void btnSearchFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFlightActionPerformed
        // TODO add your handling code here:
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        String surgePrice = txtsurgePricing.getText();
        
        if((source.equals("") || !(source.matches("[a-zA-Z]+")))||
                (destination.equals("") || !(destination.matches("[a-zA-Z]+")))||
                (surgePrice.equals("") || !(surgePrice.matches("[0-9]+")))){
            
            JOptionPane.showMessageDialog(null,"Invalid Data");
        }
        else{
            DefaultTableModel dtm = (DefaultTableModel)tblBestDealFlight.getModel();
            dtm.setRowCount(0);
        
            for(Airliner airliner : airlinerCat.getAirliners()){
                for(Schedule schedule : airliner.getSchedules()){
                    double surgePriceOfFlight = Double.parseDouble(schedule.getSurgePricing());
                    if((schedule.getSource().compareTo(source)==0)&&(schedule.getDestination().compareTo(destination)==0)&&
                            (surgePriceOfFlight <= Double.parseDouble(txtsurgePricing.getText()))){
                        Object[] row = new Object[4];
                        row[0] = schedule;
                        row[1] = schedule.getSource();
                        row[2] = schedule.getDestination();
                        row[3] = schedule.getSurgePricing();

                        dtm.addRow(row);   
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSearchFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchFlight;
    private javax.swing.JButton btnSelectAndBook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBestDeals;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSource;
    private javax.swing.JTable tblBestDealFlight;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtsurgePricing;
    // End of variables declaration//GEN-END:variables
}
