/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author eklav
 */
import Business.Person;
import Business.LicenseData;
import Business.CreditCard;
import Business.Address;
import Business.FinancialAccounts;

import javax.swing.JOptionPane;

import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private ImageIcon image;
    private BufferedImage tempImage;
    
    private Person person;
    public CreateJPanel(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJLabel = new javax.swing.JLabel();
        personJLabel = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        genderJLabel = new javax.swing.JLabel();
        mobileNumJLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        mobileNumTextField = new javax.swing.JTextField();
        licenseNumTextField = new javax.swing.JTextField();
        bloodGroupTextField = new javax.swing.JTextField();
        dateOfBirthTextField = new javax.swing.JTextField();
        fathersNameTextField = new javax.swing.JTextField();
        licenseDataJLabel = new javax.swing.JLabel();
        licencingAuthorityTextField = new javax.swing.JTextField();
        licenseNumJLabel = new javax.swing.JLabel();
        bloodGroupJLabel = new javax.swing.JLabel();
        dateOfBirthJLabel = new javax.swing.JLabel();
        fathersNameJLabel = new javax.swing.JLabel();
        licencingAuthorityNumJLabel = new javax.swing.JLabel();
        cardNumTextField = new javax.swing.JTextField();
        bankNameTextField = new javax.swing.JTextField();
        creditCompTextField = new javax.swing.JTextField();
        cardCVVTextField = new javax.swing.JTextField();
        creditCardJLabel = new javax.swing.JLabel();
        validThruTextField = new javax.swing.JTextField();
        cardNumJLabel = new javax.swing.JLabel();
        bankNameJLabel = new javax.swing.JLabel();
        creditCompJLabel = new javax.swing.JLabel();
        cardCVVJLabel = new javax.swing.JLabel();
        validThruJLabel = new javax.swing.JLabel();
        streetNameTextField = new javax.swing.JTextField();
        aptNumTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        addressJLabel = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        streetNameJLabel = new javax.swing.JLabel();
        aptNumJLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        zipCodeJLabel = new javax.swing.JLabel();
        profilePictureJLabel = new javax.swing.JLabel();
        checkingAccountNumJLabel = new javax.swing.JLabel();
        checkingCreationDateJLabel = new javax.swing.JLabel();
        checkingStatusJLabel = new javax.swing.JLabel();
        checkingDebtJLabel = new javax.swing.JLabel();
        checkingCreditJLabel = new javax.swing.JLabel();
        checkingAccountNumTextField = new javax.swing.JTextField();
        checkingCreationDateTextField = new javax.swing.JTextField();
        checkingStatusTextField = new javax.swing.JTextField();
        checkingDebtTextField = new javax.swing.JTextField();
        checkingAccountJLabel = new javax.swing.JLabel();
        checkingCreditTextField = new javax.swing.JTextField();
        savingsStatusJLabel = new javax.swing.JLabel();
        savingsDebtJLabel = new javax.swing.JLabel();
        savingsCreditJLabel = new javax.swing.JLabel();
        savingsAccountNumTextField = new javax.swing.JTextField();
        savingsCreationDateTextField = new javax.swing.JTextField();
        savingsStatusTextField = new javax.swing.JTextField();
        savingsDebtTextField = new javax.swing.JTextField();
        savingsAccountJLabel = new javax.swing.JLabel();
        savingsCreditTextField = new javax.swing.JTextField();
        savingsAccountNumJLabel = new javax.swing.JLabel();
        savingsCreationDateJLabel = new javax.swing.JLabel();
        financialAccountsJLabel = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        attachPictureJButton = new javax.swing.JButton();
        profileImageLabel = new javax.swing.JLabel();

        displayJLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        displayJLabel.setText("Create User Profile");

        personJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        personJLabel.setText("Person");

        firstNameJLabel.setText("First Name:");

        lastNameJLabel.setText("Last Name:");

        ageJLabel.setText("Age (in years):");

        genderJLabel.setText("Gender:");

        mobileNumJLabel.setText("Mobile Number:");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        genderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextFieldActionPerformed(evt);
            }
        });

        licenseNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumTextFieldActionPerformed(evt);
            }
        });

        fathersNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersNameTextFieldActionPerformed(evt);
            }
        });

        licenseDataJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        licenseDataJLabel.setText("License Details");

        licenseNumJLabel.setText("License Number:");

        bloodGroupJLabel.setText("Blood Group:");

        dateOfBirthJLabel.setText("DOB (MM/DD/YY):");

        fathersNameJLabel.setText("Father's Name:");

        licencingAuthorityNumJLabel.setText("Licencing Authority:");

        cardNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumTextFieldActionPerformed(evt);
            }
        });

        cardCVVTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardCVVTextFieldActionPerformed(evt);
            }
        });

        creditCardJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        creditCardJLabel.setText("Credit Card Details");

        cardNumJLabel.setText("Card Number:");

        bankNameJLabel.setText("Bank Name:");

        creditCompJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creditCompJLabel.setText("Credit Company (VISA/MC):");

        cardCVVJLabel.setText("Card CVV:");

        validThruJLabel.setText("Valid Through (MM/YY):");

        streetNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameTextFieldActionPerformed(evt);
            }
        });

        stateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextFieldActionPerformed(evt);
            }
        });

        addressJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressJLabel.setText("Address");

        streetNameJLabel.setText("Street Name:");

        aptNumJLabel.setText("Apartment Number:");

        cityJLabel.setText("City:");

        stateJLabel.setText("State:");

        zipCodeJLabel.setText("Zip Code:");

        profilePictureJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profilePictureJLabel.setText("Profile Picture");

        checkingAccountNumJLabel.setText("Account Number:");

        checkingCreationDateJLabel.setText("Creation Date (MM/DD/YY):");

        checkingStatusJLabel.setText("Status (Active/Not-Active):");

        checkingDebtJLabel.setText("Debt (in $):");

        checkingCreditJLabel.setText("Credit (in $):");

        checkingAccountNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccountNumTextFieldActionPerformed(evt);
            }
        });

        checkingDebtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingDebtTextFieldActionPerformed(evt);
            }
        });

        checkingAccountJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkingAccountJLabel.setText("Checking Account");

        savingsStatusJLabel.setText("Status (Active/Not-Active):");

        savingsDebtJLabel.setText("Debt (in $):");

        savingsCreditJLabel.setText("Credit (in $):");

        savingsAccountNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsAccountNumTextFieldActionPerformed(evt);
            }
        });

        savingsDebtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsDebtTextFieldActionPerformed(evt);
            }
        });

        savingsAccountJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savingsAccountJLabel.setText("Savings Account");

        savingsAccountNumJLabel.setText("Account Number:");

        savingsCreationDateJLabel.setText("Creation Date (MM/DD/YY):");

        financialAccountsJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        financialAccountsJLabel.setText("Financial Accounts");

        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        attachPictureJButton.setText("Attach Picture");
        attachPictureJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachPictureJButtonActionPerformed(evt);
            }
        });

        profileImageLabel.setLabelFor(profileImageLabel);
        profileImageLabel.setText("Image");
        profileImageLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(financialAccountsJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(profilePictureJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(attachPictureJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(profileImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displayJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(creditCardJLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cardNumJLabel)
                                            .addComponent(bankNameJLabel)
                                            .addComponent(creditCompJLabel)
                                            .addComponent(cardCVVJLabel)
                                            .addComponent(validThruJLabel))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cardNumTextField)
                                            .addComponent(bankNameTextField)
                                            .addComponent(creditCompTextField)
                                            .addComponent(cardCVVTextField)
                                            .addComponent(validThruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressJLabel)
                                    .addComponent(streetNameJLabel)
                                    .addComponent(aptNumJLabel)
                                    .addComponent(cityJLabel)
                                    .addComponent(stateJLabel)
                                    .addComponent(zipCodeJLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(streetNameTextField)
                                            .addComponent(aptNumTextField)
                                            .addComponent(cityTextField)
                                            .addComponent(stateTextField)
                                            .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(personJLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameJLabel)
                                            .addComponent(lastNameJLabel)
                                            .addComponent(ageJLabel)
                                            .addComponent(genderJLabel)
                                            .addComponent(mobileNumJLabel))
                                        .addGap(131, 131, 131)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mobileNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(licenseDataJLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(licenseNumJLabel)
                                            .addComponent(bloodGroupJLabel)
                                            .addComponent(dateOfBirthJLabel)
                                            .addComponent(fathersNameJLabel)
                                            .addComponent(licencingAuthorityNumJLabel))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(licenseNumTextField)
                                            .addComponent(bloodGroupTextField)
                                            .addComponent(dateOfBirthTextField)
                                            .addComponent(fathersNameTextField)
                                            .addComponent(licencingAuthorityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkingAccountJLabel)
                                    .addComponent(checkingAccountNumJLabel)
                                    .addComponent(checkingCreationDateJLabel)
                                    .addComponent(checkingStatusJLabel)
                                    .addComponent(checkingDebtJLabel)
                                    .addComponent(checkingCreditJLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(checkingAccountNumTextField)
                                            .addComponent(checkingCreationDateTextField)
                                            .addComponent(checkingStatusTextField)
                                            .addComponent(checkingDebtTextField)
                                            .addComponent(checkingCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savingsAccountJLabel)
                                    .addComponent(savingsAccountNumJLabel)
                                    .addComponent(savingsCreationDateJLabel)
                                    .addComponent(savingsStatusJLabel)
                                    .addComponent(savingsDebtJLabel)
                                    .addComponent(savingsCreditJLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(savingsAccountNumTextField)
                                            .addComponent(savingsCreationDateTextField)
                                            .addComponent(savingsStatusTextField)
                                            .addComponent(savingsDebtTextField)
                                            .addComponent(savingsCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(submitJButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(licenseDataJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseNumJLabel)
                            .addComponent(licenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodGroupJLabel)
                            .addComponent(bloodGroupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfBirthJLabel)
                            .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fathersNameJLabel)
                            .addComponent(fathersNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licencingAuthorityNumJLabel)
                            .addComponent(licencingAuthorityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayJLabel)
                            .addComponent(profileImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personJLabel)
                            .addComponent(profilePictureJLabel)
                            .addComponent(attachPictureJButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameJLabel)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameJLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageJLabel)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderJLabel)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobileNumJLabel)
                            .addComponent(mobileNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addressJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetNameJLabel)
                            .addComponent(streetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aptNumJLabel)
                            .addComponent(aptNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityJLabel)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stateJLabel)
                            .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipCodeJLabel)
                            .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditCardJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardNumJLabel)
                            .addComponent(cardNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bankNameJLabel)
                            .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creditCompJLabel)
                            .addComponent(creditCompTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardCVVJLabel)
                            .addComponent(cardCVVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(validThruJLabel)
                            .addComponent(validThruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingAccountJLabel)
                            .addComponent(financialAccountsJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingAccountNumJLabel)
                            .addComponent(checkingAccountNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingCreationDateJLabel)
                            .addComponent(checkingCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingStatusJLabel)
                            .addComponent(checkingStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingDebtJLabel)
                            .addComponent(checkingDebtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingCreditJLabel)
                            .addComponent(checkingCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savingsAccountJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsAccountNumJLabel)
                            .addComponent(savingsAccountNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsCreationDateJLabel)
                            .addComponent(savingsCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsStatusJLabel)
                            .addComponent(savingsStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsDebtJLabel)
                            .addComponent(savingsDebtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsCreditJLabel)
                            .addComponent(savingsCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(submitJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void genderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextFieldActionPerformed

    private void licenseNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumTextFieldActionPerformed

    private void fathersNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameTextFieldActionPerformed

    private void cardNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumTextFieldActionPerformed

    private void cardCVVTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardCVVTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardCVVTextFieldActionPerformed

    private void streetNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameTextFieldActionPerformed

    private void stateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldActionPerformed

    private void checkingAccountNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccountNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingAccountNumTextFieldActionPerformed

    private void checkingDebtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingDebtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingDebtTextFieldActionPerformed

    private void savingsAccountNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsAccountNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsAccountNumTextFieldActionPerformed

    private void savingsDebtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsDebtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsDebtTextFieldActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        person.setFirstName(firstNameTextField.getText());
        person.setLastName(lastNameTextField.getText());
        person.setAge(Integer.parseInt(ageTextField.getText()));
        person.setGender(genderTextField.getText());
        person.setMobileNumber(Integer.parseInt(mobileNumTextField.getText()));
        
        LicenseData licenseData=new LicenseData();
        licenseData.setLicenseNum(Integer.parseInt(licenseNumTextField.getText()));
        licenseData.setBloodGroup(bloodGroupTextField.getText());
        licenseData.setDateOfBirth(dateOfBirthTextField.getText());        
        licenseData.setFathersName(fathersNameTextField.getText());
        licenseData.setLicencingAuthority(licencingAuthorityTextField.getText());

        CreditCard creditCard=new CreditCard();
        creditCard.setCardNum(Integer.parseInt(cardNumTextField.getText()));
        creditCard.setBankName(bankNameTextField.getText());
        creditCard.setCreditComp(creditCompTextField.getText());
        creditCard.setCardCVV(Integer.parseInt(cardCVVTextField.getText()));
        creditCard.setValidThru(validThruTextField.getText());
        
        Address address=new Address();
        address.setStreetName(streetNameTextField.getText());
        address.setAptNum(Integer.parseInt(aptNumTextField.getText()));
        address.setCity(cityTextField.getText());
        address.setState(stateTextField.getText());
        address.setZipCode(Integer.parseInt(zipCodeTextField.getText()));
        
        FinancialAccounts checkingAccount=new FinancialAccounts();
        checkingAccount.setAccountNum(Integer.parseInt(checkingAccountNumTextField.getText()));
        checkingAccount.setCreationDate(checkingCreationDateTextField.getText());
        checkingAccount.setStatus(checkingStatusTextField.getText());
        checkingAccount.setDebt(Integer.parseInt(checkingDebtTextField.getText()));
        checkingAccount.setCredit(Integer.parseInt(checkingCreditTextField.getText()));
        
        FinancialAccounts savingsAccount=new FinancialAccounts();
        savingsAccount.setAccountNum(Integer.parseInt(savingsAccountNumTextField.getText()));
        savingsAccount.setCreationDate(savingsCreationDateTextField.getText());
        savingsAccount.setStatus(savingsStatusTextField.getText());
        savingsAccount.setDebt(Integer.parseInt(savingsDebtTextField.getText()));
        savingsAccount.setCredit(Integer.parseInt(savingsCreditTextField.getText()));
        
        person.setLicenseData(licenseData);
        person.setCreditCard(creditCard);
        person.setAddress(address);
        person.setCheckingAccount(checkingAccount);
        person.setSavingsAccount(savingsAccount);
        
        person.setImage(new ImageIcon(tempImage));//
        
        JOptionPane.showMessageDialog(null, "User Information Submitted Successfully :)");
            
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void attachPictureJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachPictureJButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int value = chooser.showOpenDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {

            try {

                tempImage = ImageIO.read(chooser.getSelectedFile());
                profileImageLabel.setIcon(new ImageIcon(tempImage));

            } catch (Exception e) {
                System.out.println("Image can't be displayed");

            }
        }
        JOptionPane.showMessageDialog(null, "Image Attached Successfully :)");
    }//GEN-LAST:event_attachPictureJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel aptNumJLabel;
    private javax.swing.JTextField aptNumTextField;
    private javax.swing.JButton attachPictureJButton;
    private javax.swing.JLabel bankNameJLabel;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JLabel bloodGroupJLabel;
    private javax.swing.JTextField bloodGroupTextField;
    private javax.swing.JLabel cardCVVJLabel;
    private javax.swing.JTextField cardCVVTextField;
    private javax.swing.JLabel cardNumJLabel;
    private javax.swing.JTextField cardNumTextField;
    private javax.swing.JLabel checkingAccountJLabel;
    private javax.swing.JLabel checkingAccountNumJLabel;
    private javax.swing.JTextField checkingAccountNumTextField;
    private javax.swing.JLabel checkingCreationDateJLabel;
    private javax.swing.JTextField checkingCreationDateTextField;
    private javax.swing.JLabel checkingCreditJLabel;
    private javax.swing.JTextField checkingCreditTextField;
    private javax.swing.JLabel checkingDebtJLabel;
    private javax.swing.JTextField checkingDebtTextField;
    private javax.swing.JLabel checkingStatusJLabel;
    private javax.swing.JTextField checkingStatusTextField;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel creditCardJLabel;
    private javax.swing.JLabel creditCompJLabel;
    private javax.swing.JTextField creditCompTextField;
    private javax.swing.JLabel dateOfBirthJLabel;
    private javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JLabel fathersNameJLabel;
    private javax.swing.JTextField fathersNameTextField;
    private javax.swing.JLabel financialAccountsJLabel;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel licencingAuthorityNumJLabel;
    private javax.swing.JTextField licencingAuthorityTextField;
    private javax.swing.JLabel licenseDataJLabel;
    private javax.swing.JLabel licenseNumJLabel;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JLabel mobileNumJLabel;
    private javax.swing.JTextField mobileNumTextField;
    private javax.swing.JLabel personJLabel;
    private javax.swing.JLabel profileImageLabel;
    private javax.swing.JLabel profilePictureJLabel;
    private javax.swing.JLabel savingsAccountJLabel;
    private javax.swing.JLabel savingsAccountNumJLabel;
    private javax.swing.JTextField savingsAccountNumTextField;
    private javax.swing.JLabel savingsCreationDateJLabel;
    private javax.swing.JTextField savingsCreationDateTextField;
    private javax.swing.JLabel savingsCreditJLabel;
    private javax.swing.JTextField savingsCreditTextField;
    private javax.swing.JLabel savingsDebtJLabel;
    private javax.swing.JTextField savingsDebtTextField;
    private javax.swing.JLabel savingsStatusJLabel;
    private javax.swing.JTextField savingsStatusTextField;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel streetNameJLabel;
    private javax.swing.JTextField streetNameTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel validThruJLabel;
    private javax.swing.JTextField validThruTextField;
    private javax.swing.JLabel zipCodeJLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
