/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Manufacture;

import userinterface.InventoryClerk.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InventoryClerkOrganization;
import Business.Organization.ManufactureInventoryClerkOrganization;
import Business.Organization.PharmacistOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VaccinationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManufactureInventoryClerkWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private ManufactureInventoryClerkOrganization labOrganization;
    private Enterprise enterprise;
    private Network network;
    private UserAccount account;
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public ManufactureInventoryClerkWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise, Network network,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        this.labOrganization = (ManufactureInventoryClerkOrganization)organization;
        this.network = network;
        this.account = account;
    }
   
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageInventoryJButton = new javax.swing.JButton();
        manageVaccineRequestsJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        manageInventoryJButton.setBackground(new java.awt.Color(203, 203, 255));
        manageInventoryJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageInventoryJButton.setText("Manage Inventory");
        manageInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryJButtonActionPerformed(evt);
            }
        });

        manageVaccineRequestsJButton.setBackground(new java.awt.Color(203, 203, 255));
        manageVaccineRequestsJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageVaccineRequestsJButton.setText("Manage Vaccine Requests");
        manageVaccineRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccineRequestsJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manufacture Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageVaccineRequestsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageInventoryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(manageInventoryJButton)
                .addGap(18, 18, 18)
                .addComponent(manageVaccineRequestsJButton)
                .addContainerGap(452, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryJButtonActionPerformed
        ManufactureInventoryManagementWorkAreaJPanel manageOrganizationJPanel = new ManufactureInventoryManagementWorkAreaJPanel(userProcessContainer,account,labOrganization,enterprise,network,business);
        userProcessContainer.add("ManufactureInventoryManagementWorkAreaJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInventoryJButtonActionPerformed

    private void manageVaccineRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccineRequestsJButtonActionPerformed
        ManufactureRequestWorkAreaJPanel manageOrganizationJPanel = new ManufactureRequestWorkAreaJPanel(userProcessContainer,account,labOrganization,enterprise,network,business);
        userProcessContainer.add("ManufactureRequestWorkAreaJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageVaccineRequestsJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageInventoryJButton;
    private javax.swing.JButton manageVaccineRequestsJButton;
    // End of variables declaration//GEN-END:variables

    
}
